// Code generated by MockGen. DO NOT EDIT.
// Source: review.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/go-park-mail-ru/2026_1_VKernelTeam/clover/services/commerce/internal/domain/dto"
	models "github.com/go-park-mail-ru/2026_1_VKernelTeam/clover/services/commerce/internal/domain/models"
	gomock "github.com/golang/mock/gomock"
)

// MockReviewProvider is a mock of ReviewProvider interface.
type MockReviewProvider struct {
	ctrl     *gomock.Controller
	recorder *MockReviewProviderMockRecorder
}

// MockReviewProviderMockRecorder is the mock recorder for MockReviewProvider.
type MockReviewProviderMockRecorder struct {
	mock *MockReviewProvider
}

// NewMockReviewProvider creates a new mock instance.
func NewMockReviewProvider(ctrl *gomock.Controller) *MockReviewProvider {
	mock := &MockReviewProvider{ctrl: ctrl}
	mock.recorder = &MockReviewProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReviewProvider) EXPECT() *MockReviewProviderMockRecorder {
	return m.recorder
}

// CreateReview mocks base method.
func (m *MockReviewProvider) CreateReview(ctx context.Context, senderID int64, req dto.CreateReviewRequest) (dto.ReviewResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReview", ctx, senderID, req)
	ret0, _ := ret[0].(dto.ReviewResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReview indicates an expected call of CreateReview.
func (mr *MockReviewProviderMockRecorder) CreateReview(ctx, senderID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReview", reflect.TypeOf((*MockReviewProvider)(nil).CreateReview), ctx, senderID, req)
}

// DeleteReview mocks base method.
func (m *MockReviewProvider) DeleteReview(ctx context.Context, userID, reviewID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteReview", ctx, userID, reviewID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteReview indicates an expected call of DeleteReview.
func (mr *MockReviewProviderMockRecorder) DeleteReview(ctx, userID, reviewID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteReview", reflect.TypeOf((*MockReviewProvider)(nil).DeleteReview), ctx, userID, reviewID)
}

// GetMyReviews mocks base method.
func (m *MockReviewProvider) GetMyReviews(ctx context.Context, senderID int64, cursor *int64, limit int) (dto.ReviewListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyReviews", ctx, senderID, cursor, limit)
	ret0, _ := ret[0].(dto.ReviewListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMyReviews indicates an expected call of GetMyReviews.
func (mr *MockReviewProviderMockRecorder) GetMyReviews(ctx, senderID, cursor, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyReviews", reflect.TypeOf((*MockReviewProvider)(nil).GetMyReviews), ctx, senderID, cursor, limit)
}

// GetUserReviews mocks base method.
func (m *MockReviewProvider) GetUserReviews(ctx context.Context, receiverID int64, cursor *int64, limit int) (dto.ReviewListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserReviews", ctx, receiverID, cursor, limit)
	ret0, _ := ret[0].(dto.ReviewListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserReviews indicates an expected call of GetUserReviews.
func (mr *MockReviewProviderMockRecorder) GetUserReviews(ctx, receiverID, cursor, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserReviews", reflect.TypeOf((*MockReviewProvider)(nil).GetUserReviews), ctx, receiverID, cursor, limit)
}

// GetUserReviewsSummary mocks base method.
func (m *MockReviewProvider) GetUserReviewsSummary(ctx context.Context, receiverID int64) (dto.ReviewSummaryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserReviewsSummary", ctx, receiverID)
	ret0, _ := ret[0].(dto.ReviewSummaryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserReviewsSummary indicates an expected call of GetUserReviewsSummary.
func (mr *MockReviewProviderMockRecorder) GetUserReviewsSummary(ctx, receiverID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserReviewsSummary", reflect.TypeOf((*MockReviewProvider)(nil).GetUserReviewsSummary), ctx, receiverID)
}

// UpdateReview mocks base method.
func (m *MockReviewProvider) UpdateReview(ctx context.Context, userID, reviewID int64, req dto.UpdateReviewRequest) (dto.ReviewResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReview", ctx, userID, reviewID, req)
	ret0, _ := ret[0].(dto.ReviewResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateReview indicates an expected call of UpdateReview.
func (mr *MockReviewProviderMockRecorder) UpdateReview(ctx, userID, reviewID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReview", reflect.TypeOf((*MockReviewProvider)(nil).UpdateReview), ctx, userID, reviewID, req)
}

// MockReviewStorage is a mock of ReviewStorage interface.
type MockReviewStorage struct {
	ctrl     *gomock.Controller
	recorder *MockReviewStorageMockRecorder
}

// MockReviewStorageMockRecorder is the mock recorder for MockReviewStorage.
type MockReviewStorageMockRecorder struct {
	mock *MockReviewStorage
}

// NewMockReviewStorage creates a new mock instance.
func NewMockReviewStorage(ctrl *gomock.Controller) *MockReviewStorage {
	mock := &MockReviewStorage{ctrl: ctrl}
	mock.recorder = &MockReviewStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReviewStorage) EXPECT() *MockReviewStorageMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockReviewStorage) Create(ctx context.Context, r *models.Review) (models.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, r)
	ret0, _ := ret[0].(models.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockReviewStorageMockRecorder) Create(ctx, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockReviewStorage)(nil).Create), ctx, r)
}

// Delete mocks base method.
func (m *MockReviewStorage) Delete(ctx context.Context, id, senderID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, senderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockReviewStorageMockRecorder) Delete(ctx, id, senderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockReviewStorage)(nil).Delete), ctx, id, senderID)
}

// ExistsPurchaseRequest mocks base method.
func (m *MockReviewStorage) ExistsPurchaseRequest(ctx context.Context, buyerID, sellerID, productID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsPurchaseRequest", ctx, buyerID, sellerID, productID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsPurchaseRequest indicates an expected call of ExistsPurchaseRequest.
func (mr *MockReviewStorageMockRecorder) ExistsPurchaseRequest(ctx, buyerID, sellerID, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsPurchaseRequest", reflect.TypeOf((*MockReviewStorage)(nil).ExistsPurchaseRequest), ctx, buyerID, sellerID, productID)
}

// GetByID mocks base method.
func (m *MockReviewStorage) GetByID(ctx context.Context, id int64) (models.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(models.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockReviewStorageMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockReviewStorage)(nil).GetByID), ctx, id)
}

// GetProductSellerID mocks base method.
func (m *MockReviewStorage) GetProductSellerID(ctx context.Context, productID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductSellerID", ctx, productID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductSellerID indicates an expected call of GetProductSellerID.
func (mr *MockReviewStorageMockRecorder) GetProductSellerID(ctx, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductSellerID", reflect.TypeOf((*MockReviewStorage)(nil).GetProductSellerID), ctx, productID)
}

// GetResponseByID mocks base method.
func (m *MockReviewStorage) GetResponseByID(ctx context.Context, reviewID int64) (dto.ReviewResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResponseByID", ctx, reviewID)
	ret0, _ := ret[0].(dto.ReviewResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResponseByID indicates an expected call of GetResponseByID.
func (mr *MockReviewStorageMockRecorder) GetResponseByID(ctx, reviewID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResponseByID", reflect.TypeOf((*MockReviewStorage)(nil).GetResponseByID), ctx, reviewID)
}

// ListByReceiver mocks base method.
func (m *MockReviewStorage) ListByReceiver(ctx context.Context, receiverID int64, cursor *int64, limit int) ([]dto.ReviewResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByReceiver", ctx, receiverID, cursor, limit)
	ret0, _ := ret[0].([]dto.ReviewResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByReceiver indicates an expected call of ListByReceiver.
func (mr *MockReviewStorageMockRecorder) ListByReceiver(ctx, receiverID, cursor, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByReceiver", reflect.TypeOf((*MockReviewStorage)(nil).ListByReceiver), ctx, receiverID, cursor, limit)
}

// ListBySender mocks base method.
func (m *MockReviewStorage) ListBySender(ctx context.Context, senderID int64, cursor *int64, limit int) ([]dto.ReviewResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBySender", ctx, senderID, cursor, limit)
	ret0, _ := ret[0].([]dto.ReviewResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBySender indicates an expected call of ListBySender.
func (mr *MockReviewStorageMockRecorder) ListBySender(ctx, senderID, cursor, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBySender", reflect.TypeOf((*MockReviewStorage)(nil).ListBySender), ctx, senderID, cursor, limit)
}

// SummaryByReceiver mocks base method.
func (m *MockReviewStorage) SummaryByReceiver(ctx context.Context, receiverID int64) (dto.ReviewSummaryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SummaryByReceiver", ctx, receiverID)
	ret0, _ := ret[0].(dto.ReviewSummaryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SummaryByReceiver indicates an expected call of SummaryByReceiver.
func (mr *MockReviewStorageMockRecorder) SummaryByReceiver(ctx, receiverID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SummaryByReceiver", reflect.TypeOf((*MockReviewStorage)(nil).SummaryByReceiver), ctx, receiverID)
}

// Update mocks base method.
func (m *MockReviewStorage) Update(ctx context.Context, id, senderID int64, rating int, content string) (models.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, senderID, rating, content)
	ret0, _ := ret[0].(models.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockReviewStorageMockRecorder) Update(ctx, id, senderID, rating, content interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockReviewStorage)(nil).Update), ctx, id, senderID, rating, content)
}
