// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/chat/chat.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/go-park-mail-ru/2026_1_VKernelTeam/clover/internal/domain/dto"
	models "github.com/go-park-mail-ru/2026_1_VKernelTeam/clover/internal/domain/models"
	gomock "github.com/golang/mock/gomock"
)

// MockChatProvider is a mock of ChatProvider interface.
type MockChatProvider struct {
	ctrl     *gomock.Controller
	recorder *MockChatProviderMockRecorder
}

// MockChatProviderMockRecorder is the mock recorder for MockChatProvider.
type MockChatProviderMockRecorder struct {
	mock *MockChatProvider
}

// NewMockChatProvider creates a new mock instance.
func NewMockChatProvider(ctrl *gomock.Controller) *MockChatProvider {
	mock := &MockChatProvider{ctrl: ctrl}
	mock.recorder = &MockChatProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatProvider) EXPECT() *MockChatProviderMockRecorder {
	return m.recorder
}

// CompletePurchase mocks base method.
func (m *MockChatProvider) CompletePurchase(ctx context.Context, buyerID, productID, price int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompletePurchase", ctx, buyerID, productID, price)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompletePurchase indicates an expected call of CompletePurchase.
func (mr *MockChatProviderMockRecorder) CompletePurchase(ctx, buyerID, productID, price interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompletePurchase", reflect.TypeOf((*MockChatProvider)(nil).CompletePurchase), ctx, buyerID, productID, price)
}

// CreateMessage mocks base method.
func (m *MockChatProvider) CreateMessage(ctx context.Context, message *models.Message) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMessage", ctx, message)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMessage indicates an expected call of CreateMessage.
func (mr *MockChatProviderMockRecorder) CreateMessage(ctx, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMessage", reflect.TypeOf((*MockChatProvider)(nil).CreateMessage), ctx, message)
}

// GetChatByID mocks base method.
func (m *MockChatProvider) GetChatByID(ctx context.Context, chatID int64) (models.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatByID", ctx, chatID)
	ret0, _ := ret[0].(models.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatByID indicates an expected call of GetChatByID.
func (mr *MockChatProviderMockRecorder) GetChatByID(ctx, chatID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatByID", reflect.TypeOf((*MockChatProvider)(nil).GetChatByID), ctx, chatID)
}

// GetChatDetail mocks base method.
func (m *MockChatProvider) GetChatDetail(ctx context.Context, chatID, userID int64) (dto.ChatDetailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatDetail", ctx, chatID, userID)
	ret0, _ := ret[0].(dto.ChatDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatDetail indicates an expected call of GetChatDetail.
func (mr *MockChatProviderMockRecorder) GetChatDetail(ctx, chatID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatDetail", reflect.TypeOf((*MockChatProvider)(nil).GetChatDetail), ctx, chatID, userID)
}

// GetChatsByUserID mocks base method.
func (m *MockChatProvider) GetChatsByUserID(ctx context.Context, userID int64) ([]dto.ChatPreview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatsByUserID", ctx, userID)
	ret0, _ := ret[0].([]dto.ChatPreview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatsByUserID indicates an expected call of GetChatsByUserID.
func (mr *MockChatProviderMockRecorder) GetChatsByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatsByUserID", reflect.TypeOf((*MockChatProvider)(nil).GetChatsByUserID), ctx, userID)
}

// GetOrCreateChat mocks base method.
func (m *MockChatProvider) GetOrCreateChat(ctx context.Context, adID, buyerID, sellerID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateChat", ctx, adID, buyerID, sellerID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreateChat indicates an expected call of GetOrCreateChat.
func (mr *MockChatProviderMockRecorder) GetOrCreateChat(ctx, adID, buyerID, sellerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateChat", reflect.TypeOf((*MockChatProvider)(nil).GetOrCreateChat), ctx, adID, buyerID, sellerID)
}

// MockAdProvider is a mock of AdProvider interface.
type MockAdProvider struct {
	ctrl     *gomock.Controller
	recorder *MockAdProviderMockRecorder
}

// MockAdProviderMockRecorder is the mock recorder for MockAdProvider.
type MockAdProviderMockRecorder struct {
	mock *MockAdProvider
}

// NewMockAdProvider creates a new mock instance.
func NewMockAdProvider(ctrl *gomock.Controller) *MockAdProvider {
	mock := &MockAdProvider{ctrl: ctrl}
	mock.recorder = &MockAdProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdProvider) EXPECT() *MockAdProviderMockRecorder {
	return m.recorder
}

// GetAdByID mocks base method.
func (m *MockAdProvider) GetAdByID(ctx context.Context, id int64) (models.Ad, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdByID", ctx, id)
	ret0, _ := ret[0].(models.Ad)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdByID indicates an expected call of GetAdByID.
func (mr *MockAdProviderMockRecorder) GetAdByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdByID", reflect.TypeOf((*MockAdProvider)(nil).GetAdByID), ctx, id)
}
