FROM golang:1.26.0-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o auth-service ./services/auth/cmd/server/main.go

FROM alpine:3.20

WORKDIR /app

COPY --from=builder /app/auth-service .
COPY services/auth/config ./config

EXPOSE 8001 9001

ENTRYPOINT ["./auth-service", "--config=./config/local.json"]
