services:
  clover:
    container_name: clover
    build:
      context: ..
      dockerfile: ./deployments/Dockerfile
    env_file:
      - ../.env
    environment:
      - DATABASE_DSN=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      - REDIS_ADDR=redis:6379
    restart: always
    ports:
      - 8000:8000
    volumes:
      # путь_на_хосте : путь_в_контейнере
      - ../static:/app/static
      - ../storage:/app/storage
    depends_on:
      redis:
        condition: service_started
      db_migrate:
        condition: service_completed_successfully
      
  db:
    image: postgres:17-alpine
    container_name: postgres_clover
    env_file:
      - ../.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d clover"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  db_migrate:
    image: migrate/migrate
    container_name: db_migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../internal/repository/postgres/migrations:/migrations
    command:
      - -path=/migrations
      - -database=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      - up

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  pgdata:
