FROM golang:1.26.0-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o support-service ./services/support/cmd/server/main.go

FROM alpine:3.20

WORKDIR /app

COPY --from=builder /app/support-service .
COPY services/support/config ./config

EXPOSE 8002

ENTRYPOINT ["./support-service", "--config=./config/local.json"]
