FROM golang:1.26.0-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o catalog-service ./services/catalog/cmd/server/main.go

FROM alpine:3.20

WORKDIR /app

COPY --from=builder /app/catalog-service .
COPY services/catalog/config ./config

EXPOSE 8004 9004

ENTRYPOINT ["./catalog-service", "--config=./config/local.json"]
