apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    jsonData:
      host: clickhouse
      port: 8123
      protocol: http
      secure: false
      username: ${CLICKHOUSE_USER}
      defaultDatabase: logs
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}
    editable: true

  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    jsonData:
      timeInterval: "15s"
    editable: true
