// Code generated by MockGen. DO NOT EDIT.
// Source: ../../../../../proto/gen/catalog/v1/catalog_grpc.pb.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	catalogv1 "github.com/go-park-mail-ru/2026_1_VKernelTeam/clover/proto/gen/catalog/v1"
	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockCatalogServiceClient is a mock of CatalogServiceClient interface.
type MockCatalogServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogServiceClientMockRecorder
}

// MockCatalogServiceClientMockRecorder is the mock recorder for MockCatalogServiceClient.
type MockCatalogServiceClientMockRecorder struct {
	mock *MockCatalogServiceClient
}

// NewMockCatalogServiceClient creates a new mock instance.
func NewMockCatalogServiceClient(ctrl *gomock.Controller) *MockCatalogServiceClient {
	mock := &MockCatalogServiceClient{ctrl: ctrl}
	mock.recorder = &MockCatalogServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalogServiceClient) EXPECT() *MockCatalogServiceClientMockRecorder {
	return m.recorder
}

// CheckAdStatus mocks base method.
func (m *MockCatalogServiceClient) CheckAdStatus(ctx context.Context, in *catalogv1.CheckAdStatusRequest, opts ...grpc.CallOption) (*catalogv1.CheckAdStatusResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CheckAdStatus", varargs...)
	ret0, _ := ret[0].(*catalogv1.CheckAdStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAdStatus indicates an expected call of CheckAdStatus.
func (mr *MockCatalogServiceClientMockRecorder) CheckAdStatus(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAdStatus", reflect.TypeOf((*MockCatalogServiceClient)(nil).CheckAdStatus), varargs...)
}

// GetAd mocks base method.
func (m *MockCatalogServiceClient) GetAd(ctx context.Context, in *catalogv1.GetAdRequest, opts ...grpc.CallOption) (*catalogv1.AdResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAd", varargs...)
	ret0, _ := ret[0].(*catalogv1.AdResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAd indicates an expected call of GetAd.
func (mr *MockCatalogServiceClientMockRecorder) GetAd(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAd", reflect.TypeOf((*MockCatalogServiceClient)(nil).GetAd), varargs...)
}

// GetAdsByIDs mocks base method.
func (m *MockCatalogServiceClient) GetAdsByIDs(ctx context.Context, in *catalogv1.GetAdsByIDsRequest, opts ...grpc.CallOption) (*catalogv1.GetAdsByIDsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAdsByIDs", varargs...)
	ret0, _ := ret[0].(*catalogv1.GetAdsByIDsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdsByIDs indicates an expected call of GetAdsByIDs.
func (mr *MockCatalogServiceClientMockRecorder) GetAdsByIDs(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdsByIDs", reflect.TypeOf((*MockCatalogServiceClient)(nil).GetAdsByIDs), varargs...)
}

// UpdateAdStatus mocks base method.
func (m *MockCatalogServiceClient) UpdateAdStatus(ctx context.Context, in *catalogv1.UpdateAdStatusRequest, opts ...grpc.CallOption) (*catalogv1.UpdateAdStatusResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateAdStatus", varargs...)
	ret0, _ := ret[0].(*catalogv1.UpdateAdStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAdStatus indicates an expected call of UpdateAdStatus.
func (mr *MockCatalogServiceClientMockRecorder) UpdateAdStatus(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAdStatus", reflect.TypeOf((*MockCatalogServiceClient)(nil).UpdateAdStatus), varargs...)
}

// MockCatalogServiceServer is a mock of CatalogServiceServer interface.
type MockCatalogServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogServiceServerMockRecorder
}

// MockCatalogServiceServerMockRecorder is the mock recorder for MockCatalogServiceServer.
type MockCatalogServiceServerMockRecorder struct {
	mock *MockCatalogServiceServer
}

// NewMockCatalogServiceServer creates a new mock instance.
func NewMockCatalogServiceServer(ctrl *gomock.Controller) *MockCatalogServiceServer {
	mock := &MockCatalogServiceServer{ctrl: ctrl}
	mock.recorder = &MockCatalogServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalogServiceServer) EXPECT() *MockCatalogServiceServerMockRecorder {
	return m.recorder
}

// CheckAdStatus mocks base method.
func (m *MockCatalogServiceServer) CheckAdStatus(arg0 context.Context, arg1 *catalogv1.CheckAdStatusRequest) (*catalogv1.CheckAdStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAdStatus", arg0, arg1)
	ret0, _ := ret[0].(*catalogv1.CheckAdStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAdStatus indicates an expected call of CheckAdStatus.
func (mr *MockCatalogServiceServerMockRecorder) CheckAdStatus(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAdStatus", reflect.TypeOf((*MockCatalogServiceServer)(nil).CheckAdStatus), arg0, arg1)
}

// GetAd mocks base method.
func (m *MockCatalogServiceServer) GetAd(arg0 context.Context, arg1 *catalogv1.GetAdRequest) (*catalogv1.AdResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAd", arg0, arg1)
	ret0, _ := ret[0].(*catalogv1.AdResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAd indicates an expected call of GetAd.
func (mr *MockCatalogServiceServerMockRecorder) GetAd(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAd", reflect.TypeOf((*MockCatalogServiceServer)(nil).GetAd), arg0, arg1)
}

// GetAdsByIDs mocks base method.
func (m *MockCatalogServiceServer) GetAdsByIDs(arg0 context.Context, arg1 *catalogv1.GetAdsByIDsRequest) (*catalogv1.GetAdsByIDsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdsByIDs", arg0, arg1)
	ret0, _ := ret[0].(*catalogv1.GetAdsByIDsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdsByIDs indicates an expected call of GetAdsByIDs.
func (mr *MockCatalogServiceServerMockRecorder) GetAdsByIDs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdsByIDs", reflect.TypeOf((*MockCatalogServiceServer)(nil).GetAdsByIDs), arg0, arg1)
}

// UpdateAdStatus mocks base method.
func (m *MockCatalogServiceServer) UpdateAdStatus(arg0 context.Context, arg1 *catalogv1.UpdateAdStatusRequest) (*catalogv1.UpdateAdStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAdStatus", arg0, arg1)
	ret0, _ := ret[0].(*catalogv1.UpdateAdStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAdStatus indicates an expected call of UpdateAdStatus.
func (mr *MockCatalogServiceServerMockRecorder) UpdateAdStatus(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAdStatus", reflect.TypeOf((*MockCatalogServiceServer)(nil).UpdateAdStatus), arg0, arg1)
}

// mustEmbedUnimplementedCatalogServiceServer mocks base method.
func (m *MockCatalogServiceServer) mustEmbedUnimplementedCatalogServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedCatalogServiceServer")
}

// mustEmbedUnimplementedCatalogServiceServer indicates an expected call of mustEmbedUnimplementedCatalogServiceServer.
func (mr *MockCatalogServiceServerMockRecorder) mustEmbedUnimplementedCatalogServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedCatalogServiceServer", reflect.TypeOf((*MockCatalogServiceServer)(nil).mustEmbedUnimplementedCatalogServiceServer))
}

// MockUnsafeCatalogServiceServer is a mock of UnsafeCatalogServiceServer interface.
type MockUnsafeCatalogServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeCatalogServiceServerMockRecorder
}

// MockUnsafeCatalogServiceServerMockRecorder is the mock recorder for MockUnsafeCatalogServiceServer.
type MockUnsafeCatalogServiceServerMockRecorder struct {
	mock *MockUnsafeCatalogServiceServer
}

// NewMockUnsafeCatalogServiceServer creates a new mock instance.
func NewMockUnsafeCatalogServiceServer(ctrl *gomock.Controller) *MockUnsafeCatalogServiceServer {
	mock := &MockUnsafeCatalogServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeCatalogServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeCatalogServiceServer) EXPECT() *MockUnsafeCatalogServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedCatalogServiceServer mocks base method.
func (m *MockUnsafeCatalogServiceServer) mustEmbedUnimplementedCatalogServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedCatalogServiceServer")
}

// mustEmbedUnimplementedCatalogServiceServer indicates an expected call of mustEmbedUnimplementedCatalogServiceServer.
func (mr *MockUnsafeCatalogServiceServerMockRecorder) mustEmbedUnimplementedCatalogServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedCatalogServiceServer", reflect.TypeOf((*MockUnsafeCatalogServiceServer)(nil).mustEmbedUnimplementedCatalogServiceServer))
}
