// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package kafka

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson692db02bDecodeGithubComGoParkMailRu20261VKernelTeamCloverPkgSharedKafka(in *jlexer.Lexer, out *UserPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson692db02bEncodeGithubComGoParkMailRu20261VKernelTeamCloverPkgSharedKafka(out *jwriter.Writer, in UserPayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.UserID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UserPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson692db02bEncodeGithubComGoParkMailRu20261VKernelTeamCloverPkgSharedKafka(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UserPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson692db02bEncodeGithubComGoParkMailRu20261VKernelTeamCloverPkgSharedKafka(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UserPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson692db02bDecodeGithubComGoParkMailRu20261VKernelTeamCloverPkgSharedKafka(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UserPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson692db02bDecodeGithubComGoParkMailRu20261VKernelTeamCloverPkgSharedKafka(l, v)
}
func easyjson692db02bDecodeGithubComGoParkMailRu20261VKernelTeamCloverPkgSharedKafka1(in *jlexer.Lexer, out *Event) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "event_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EventType = string(in.String())
			}
		case "event_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EventID = string(in.String())
			}
		case "timestamp":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Timestamp).UnmarshalJSON(data))
				}
			}
		case "payload":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Payload).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson692db02bEncodeGithubComGoParkMailRu20261VKernelTeamCloverPkgSharedKafka1(out *jwriter.Writer, in Event) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"event_type\":"
		out.RawString(prefix[1:])
		out.String(string(in.EventType))
	}
	{
		const prefix string = ",\"event_id\":"
		out.RawString(prefix)
		out.String(string(in.EventID))
	}
	{
		const prefix string = ",\"timestamp\":"
		out.RawString(prefix)
		out.Raw((in.Timestamp).MarshalJSON())
	}
	{
		const prefix string = ",\"payload\":"
		out.RawString(prefix)
		out.Raw((in.Payload).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Event) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson692db02bEncodeGithubComGoParkMailRu20261VKernelTeamCloverPkgSharedKafka1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Event) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson692db02bEncodeGithubComGoParkMailRu20261VKernelTeamCloverPkgSharedKafka1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Event) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson692db02bDecodeGithubComGoParkMailRu20261VKernelTeamCloverPkgSharedKafka1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Event) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson692db02bDecodeGithubComGoParkMailRu20261VKernelTeamCloverPkgSharedKafka1(l, v)
}
func easyjson692db02bDecodeGithubComGoParkMailRu20261VKernelTeamCloverPkgSharedKafka2(in *jlexer.Lexer, out *AdPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "ad_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AdID = int64(in.Int64())
			}
		case "buyer_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BuyerID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson692db02bEncodeGithubComGoParkMailRu20261VKernelTeamCloverPkgSharedKafka2(out *jwriter.Writer, in AdPayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ad_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.AdID))
	}
	if in.BuyerID != 0 {
		const prefix string = ",\"buyer_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.BuyerID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AdPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson692db02bEncodeGithubComGoParkMailRu20261VKernelTeamCloverPkgSharedKafka2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AdPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson692db02bEncodeGithubComGoParkMailRu20261VKernelTeamCloverPkgSharedKafka2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AdPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson692db02bDecodeGithubComGoParkMailRu20261VKernelTeamCloverPkgSharedKafka2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AdPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson692db02bDecodeGithubComGoParkMailRu20261VKernelTeamCloverPkgSharedKafka2(l, v)
}
