// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/go-park-mail-ru/2026_1_VKernelTeam/clover/internal/domain/dto"
	models "github.com/go-park-mail-ru/2026_1_VKernelTeam/clover/internal/domain/models"
	gomock "github.com/golang/mock/gomock"
)

// MockCartProvider is a mock of CartProvider interface.
type MockCartProvider struct {
	ctrl     *gomock.Controller
	recorder *MockCartProviderMockRecorder
}

// MockCartProviderMockRecorder is the mock recorder for MockCartProvider.
type MockCartProviderMockRecorder struct {
	mock *MockCartProvider
}

// NewMockCartProvider creates a new mock instance.
func NewMockCartProvider(ctrl *gomock.Controller) *MockCartProvider {
	mock := &MockCartProvider{ctrl: ctrl}
	mock.recorder = &MockCartProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCartProvider) EXPECT() *MockCartProviderMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockCartProvider) Add(ctx context.Context, userID, productID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, userID, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockCartProviderMockRecorder) Add(ctx, userID, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockCartProvider)(nil).Add), ctx, userID, productID)
}

// Checkout mocks base method.
func (m *MockCartProvider) Checkout(ctx context.Context, buyerID int64) ([]int64, map[int64]*dto.SellerContact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Checkout", ctx, buyerID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(map[int64]*dto.SellerContact)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Checkout indicates an expected call of Checkout.
func (mr *MockCartProviderMockRecorder) Checkout(ctx, buyerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Checkout", reflect.TypeOf((*MockCartProvider)(nil).Checkout), ctx, buyerID)
}

// Clear mocks base method.
func (m *MockCartProvider) Clear(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clear", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Clear indicates an expected call of Clear.
func (mr *MockCartProviderMockRecorder) Clear(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockCartProvider)(nil).Clear), ctx, userID)
}

// GetByUserID mocks base method.
func (m *MockCartProvider) GetByUserID(ctx context.Context, userID int64) ([]dto.CartItemResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].([]dto.CartItemResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockCartProviderMockRecorder) GetByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockCartProvider)(nil).GetByUserID), ctx, userID)
}

// Remove mocks base method.
func (m *MockCartProvider) Remove(ctx context.Context, userID, productID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, userID, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockCartProviderMockRecorder) Remove(ctx, userID, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockCartProvider)(nil).Remove), ctx, userID, productID)
}

// MockAdsProvider is a mock of AdsProvider interface.
type MockAdsProvider struct {
	ctrl     *gomock.Controller
	recorder *MockAdsProviderMockRecorder
}

// MockAdsProviderMockRecorder is the mock recorder for MockAdsProvider.
type MockAdsProviderMockRecorder struct {
	mock *MockAdsProvider
}

// NewMockAdsProvider creates a new mock instance.
func NewMockAdsProvider(ctrl *gomock.Controller) *MockAdsProvider {
	mock := &MockAdsProvider{ctrl: ctrl}
	mock.recorder = &MockAdsProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdsProvider) EXPECT() *MockAdsProviderMockRecorder {
	return m.recorder
}

// GetAdByID mocks base method.
func (m *MockAdsProvider) GetAdByID(ctx context.Context, id int64) (models.Ad, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdByID", ctx, id)
	ret0, _ := ret[0].(models.Ad)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdByID indicates an expected call of GetAdByID.
func (mr *MockAdsProviderMockRecorder) GetAdByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdByID", reflect.TypeOf((*MockAdsProvider)(nil).GetAdByID), ctx, id)
}
