version: "2"

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - bodyclose
    - noctx
    - errcheck
    - gocognit
    - goconst
    - unused
  settings:
    gocognit:
      min-complexity: 60

formatters:
  enable:
    - gofmt
    - goimports
