version: "2"
linters-settings:
  gocognit:
    min-complexity: 60

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - bodyclose
    - noctx
    - errcheck
    - gocognit
    - goconst
    - unused

formatters:
  enable:
    - gofmt
    - goimports
