version: "2"

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - bodyclose
    - noctx
    - errcheck
    - gocognit
    - goconst
    - unused
  settings:
    gocognit:
      min-complexity: 60
  exclusions:
    paths:
      - ".*_easyjson\\.go$"

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    paths:
      - ".*_easyjson\\.go$"
