// Code generated by MockGen. DO NOT EDIT.
// Source: auth.go

// Package mock_auth is a generated GoMock package.
package mock_auth

import (
	context "context"
	multipart "mime/multipart"
	reflect "reflect"
	time "time"

	models "github.com/go-park-mail-ru/2026_1_VKernelTeam/clover/internal/domain/models"
	gomock "github.com/golang/mock/gomock"
)

// MockTokenRevoker is a mock of TokenRevoker interface.
type MockTokenRevoker struct {
	ctrl     *gomock.Controller
	recorder *MockTokenRevokerMockRecorder
}

// MockTokenRevokerMockRecorder is the mock recorder for MockTokenRevoker.
type MockTokenRevokerMockRecorder struct {
	mock *MockTokenRevoker
}

// NewMockTokenRevoker creates a new mock instance.
func NewMockTokenRevoker(ctrl *gomock.Controller) *MockTokenRevoker {
	mock := &MockTokenRevoker{ctrl: ctrl}
	mock.recorder = &MockTokenRevokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenRevoker) EXPECT() *MockTokenRevokerMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockTokenRevoker) Add(jti string, exp time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Add", jti, exp)
}

// Add indicates an expected call of Add.
func (mr *MockTokenRevokerMockRecorder) Add(jti, exp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockTokenRevoker)(nil).Add), jti, exp)
}

// MockRefreshStorage is a mock of RefreshStorage interface.
type MockRefreshStorage struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshStorageMockRecorder
}

// MockRefreshStorageMockRecorder is the mock recorder for MockRefreshStorage.
type MockRefreshStorageMockRecorder struct {
	mock *MockRefreshStorage
}

// NewMockRefreshStorage creates a new mock instance.
func NewMockRefreshStorage(ctrl *gomock.Controller) *MockRefreshStorage {
	mock := &MockRefreshStorage{ctrl: ctrl}
	mock.recorder = &MockRefreshStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshStorage) EXPECT() *MockRefreshStorageMockRecorder {
	return m.recorder
}

// DeleteRefresh mocks base method.
func (m *MockRefreshStorage) DeleteRefresh(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRefresh", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRefresh indicates an expected call of DeleteRefresh.
func (mr *MockRefreshStorageMockRecorder) DeleteRefresh(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRefresh", reflect.TypeOf((*MockRefreshStorage)(nil).DeleteRefresh), ctx, token)
}

// GetRefresh mocks base method.
func (m *MockRefreshStorage) GetRefresh(ctx context.Context, token string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefresh", ctx, token)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefresh indicates an expected call of GetRefresh.
func (mr *MockRefreshStorageMockRecorder) GetRefresh(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefresh", reflect.TypeOf((*MockRefreshStorage)(nil).GetRefresh), ctx, token)
}

// SaveRefresh mocks base method.
func (m *MockRefreshStorage) SaveRefresh(ctx context.Context, token string, userID int64, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRefresh", ctx, token, userID, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRefresh indicates an expected call of SaveRefresh.
func (mr *MockRefreshStorageMockRecorder) SaveRefresh(ctx, token, userID, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRefresh", reflect.TypeOf((*MockRefreshStorage)(nil).SaveRefresh), ctx, token, userID, ttl)
}

// MockFileStorage is a mock of FileStorage interface.
type MockFileStorage struct {
	ctrl     *gomock.Controller
	recorder *MockFileStorageMockRecorder
}

// MockFileStorageMockRecorder is the mock recorder for MockFileStorage.
type MockFileStorageMockRecorder struct {
	mock *MockFileStorage
}

// NewMockFileStorage creates a new mock instance.
func NewMockFileStorage(ctrl *gomock.Controller) *MockFileStorage {
	mock := &MockFileStorage{ctrl: ctrl}
	mock.recorder = &MockFileStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileStorage) EXPECT() *MockFileStorageMockRecorder {
	return m.recorder
}

// DeleteFile mocks base method.
func (m *MockFileStorage) DeleteFile(ctx context.Context, fileURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", ctx, fileURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockFileStorageMockRecorder) DeleteFile(ctx, fileURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockFileStorage)(nil).DeleteFile), ctx, fileURL)
}

// UploadFile mocks base method.
func (m *MockFileStorage) UploadFile(ctx context.Context, file multipart.File, folder, extension string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", ctx, file, folder, extension)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockFileStorageMockRecorder) UploadFile(ctx, file, folder, extension interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockFileStorage)(nil).UploadFile), ctx, file, folder, extension)
}

// MockUserProviderSaver is a mock of UserProviderSaver interface.
type MockUserProviderSaver struct {
	ctrl     *gomock.Controller
	recorder *MockUserProviderSaverMockRecorder
}

// MockUserProviderSaverMockRecorder is the mock recorder for MockUserProviderSaver.
type MockUserProviderSaverMockRecorder struct {
	mock *MockUserProviderSaver
}

// NewMockUserProviderSaver creates a new mock instance.
func NewMockUserProviderSaver(ctrl *gomock.Controller) *MockUserProviderSaver {
	mock := &MockUserProviderSaver{ctrl: ctrl}
	mock.recorder = &MockUserProviderSaverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserProviderSaver) EXPECT() *MockUserProviderSaverMockRecorder {
	return m.recorder
}

// SaveUser mocks base method.
func (m *MockUserProviderSaver) SaveUser(ctx context.Context, email string, passHash []byte, name string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUser", ctx, email, passHash, name)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveUser indicates an expected call of SaveUser.
func (mr *MockUserProviderSaverMockRecorder) SaveUser(ctx, email, passHash, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUser", reflect.TypeOf((*MockUserProviderSaver)(nil).SaveUser), ctx, email, passHash, name)
}

// UpdateAvatarPath mocks base method.
func (m *MockUserProviderSaver) UpdateAvatarPath(ctx context.Context, userID int64, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAvatarPath", ctx, userID, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAvatarPath indicates an expected call of UpdateAvatarPath.
func (mr *MockUserProviderSaverMockRecorder) UpdateAvatarPath(ctx, userID, path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAvatarPath", reflect.TypeOf((*MockUserProviderSaver)(nil).UpdateAvatarPath), ctx, userID, path)
}

// UpdateUser mocks base method.
func (m *MockUserProviderSaver) UpdateUser(ctx context.Context, userID int64, name string) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, userID, name)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserProviderSaverMockRecorder) UpdateUser(ctx, userID, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserProviderSaver)(nil).UpdateUser), ctx, userID, name)
}

// User mocks base method.
func (m *MockUserProviderSaver) User(ctx context.Context, email string) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "User", ctx, email)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// User indicates an expected call of User.
func (mr *MockUserProviderSaverMockRecorder) User(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "User", reflect.TypeOf((*MockUserProviderSaver)(nil).User), ctx, email)
}

// UserByID mocks base method.
func (m *MockUserProviderSaver) UserByID(ctx context.Context, userID int64) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserByID", ctx, userID)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserByID indicates an expected call of UserByID.
func (mr *MockUserProviderSaverMockRecorder) UserByID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserByID", reflect.TypeOf((*MockUserProviderSaver)(nil).UserByID), ctx, userID)
}
