// Code generated by MockGen. DO NOT EDIT.
// Source: reviews.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/go-park-mail-ru/2026_1_VKernelTeam/clover/services/commerce/internal/domain/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockReviewProvider is a mock of ReviewProvider interface.
type MockReviewProvider struct {
	ctrl     *gomock.Controller
	recorder *MockReviewProviderMockRecorder
}

// MockReviewProviderMockRecorder is the mock recorder for MockReviewProvider.
type MockReviewProviderMockRecorder struct {
	mock *MockReviewProvider
}

// NewMockReviewProvider creates a new mock instance.
func NewMockReviewProvider(ctrl *gomock.Controller) *MockReviewProvider {
	mock := &MockReviewProvider{ctrl: ctrl}
	mock.recorder = &MockReviewProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReviewProvider) EXPECT() *MockReviewProviderMockRecorder {
	return m.recorder
}

// CreateReview mocks base method.
func (m *MockReviewProvider) CreateReview(ctx context.Context, senderID int64, req dto.CreateReviewRequest) (dto.ReviewResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReview", ctx, senderID, req)
	ret0, _ := ret[0].(dto.ReviewResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReview indicates an expected call of CreateReview.
func (mr *MockReviewProviderMockRecorder) CreateReview(ctx, senderID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReview", reflect.TypeOf((*MockReviewProvider)(nil).CreateReview), ctx, senderID, req)
}

// DeleteReview mocks base method.
func (m *MockReviewProvider) DeleteReview(ctx context.Context, userID, reviewID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteReview", ctx, userID, reviewID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteReview indicates an expected call of DeleteReview.
func (mr *MockReviewProviderMockRecorder) DeleteReview(ctx, userID, reviewID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteReview", reflect.TypeOf((*MockReviewProvider)(nil).DeleteReview), ctx, userID, reviewID)
}

// GetMyReviews mocks base method.
func (m *MockReviewProvider) GetMyReviews(ctx context.Context, senderID int64, cursor *int64, limit int) (dto.ReviewListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyReviews", ctx, senderID, cursor, limit)
	ret0, _ := ret[0].(dto.ReviewListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMyReviews indicates an expected call of GetMyReviews.
func (mr *MockReviewProviderMockRecorder) GetMyReviews(ctx, senderID, cursor, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyReviews", reflect.TypeOf((*MockReviewProvider)(nil).GetMyReviews), ctx, senderID, cursor, limit)
}

// GetUserReviews mocks base method.
func (m *MockReviewProvider) GetUserReviews(ctx context.Context, receiverID int64, cursor *int64, limit int) (dto.ReviewListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserReviews", ctx, receiverID, cursor, limit)
	ret0, _ := ret[0].(dto.ReviewListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserReviews indicates an expected call of GetUserReviews.
func (mr *MockReviewProviderMockRecorder) GetUserReviews(ctx, receiverID, cursor, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserReviews", reflect.TypeOf((*MockReviewProvider)(nil).GetUserReviews), ctx, receiverID, cursor, limit)
}

// GetUserReviewsSummary mocks base method.
func (m *MockReviewProvider) GetUserReviewsSummary(ctx context.Context, receiverID int64) (dto.ReviewSummaryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserReviewsSummary", ctx, receiverID)
	ret0, _ := ret[0].(dto.ReviewSummaryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserReviewsSummary indicates an expected call of GetUserReviewsSummary.
func (mr *MockReviewProviderMockRecorder) GetUserReviewsSummary(ctx, receiverID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserReviewsSummary", reflect.TypeOf((*MockReviewProvider)(nil).GetUserReviewsSummary), ctx, receiverID)
}

// UpdateReview mocks base method.
func (m *MockReviewProvider) UpdateReview(ctx context.Context, userID, reviewID int64, req dto.UpdateReviewRequest) (dto.ReviewResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReview", ctx, userID, reviewID, req)
	ret0, _ := ret[0].(dto.ReviewResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateReview indicates an expected call of UpdateReview.
func (mr *MockReviewProviderMockRecorder) UpdateReview(ctx, userID, reviewID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReview", reflect.TypeOf((*MockReviewProvider)(nil).UpdateReview), ctx, userID, reviewID, req)
}
