// Code generated by MockGen. DO NOT EDIT.
// Source: services/commerce/internal/delivery/handlers/wallet.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/go-park-mail-ru/2026_1_VKernelTeam/clover/services/commerce/internal/domain/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockWalletService is a mock of WalletService interface.
type MockWalletService struct {
	ctrl     *gomock.Controller
	recorder *MockWalletServiceMockRecorder
}

// MockWalletServiceMockRecorder is the mock recorder for MockWalletService.
type MockWalletServiceMockRecorder struct {
	mock *MockWalletService
}

// NewMockWalletService creates a new mock instance.
func NewMockWalletService(ctrl *gomock.Controller) *MockWalletService {
	mock := &MockWalletService{ctrl: ctrl}
	mock.recorder = &MockWalletServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletService) EXPECT() *MockWalletServiceMockRecorder {
	return m.recorder
}

// GetBalance mocks base method.
func (m *MockWalletService) GetBalance(ctx context.Context, userID int64) (dto.WalletResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, userID)
	ret0, _ := ret[0].(dto.WalletResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockWalletServiceMockRecorder) GetBalance(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockWalletService)(nil).GetBalance), ctx, userID)
}

// GetPaymentStatus mocks base method.
func (m *MockWalletService) GetPaymentStatus(ctx context.Context, userID, paymentID int64) (dto.PaymentStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentStatus", ctx, userID, paymentID)
	ret0, _ := ret[0].(dto.PaymentStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentStatus indicates an expected call of GetPaymentStatus.
func (mr *MockWalletServiceMockRecorder) GetPaymentStatus(ctx, userID, paymentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentStatus", reflect.TypeOf((*MockWalletService)(nil).GetPaymentStatus), ctx, userID, paymentID)
}

// ListTransactions mocks base method.
func (m *MockWalletService) ListTransactions(ctx context.Context, userID, cursor int64, limit int) (dto.WalletTransactionListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransactions", ctx, userID, cursor, limit)
	ret0, _ := ret[0].(dto.WalletTransactionListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransactions indicates an expected call of ListTransactions.
func (mr *MockWalletServiceMockRecorder) ListTransactions(ctx, userID, cursor, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactions", reflect.TypeOf((*MockWalletService)(nil).ListTransactions), ctx, userID, cursor, limit)
}

// Topup mocks base method.
func (m *MockWalletService) Topup(ctx context.Context, userID, amount int64, idempotencyKey string) (dto.TopupWalletResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Topup", ctx, userID, amount, idempotencyKey)
	ret0, _ := ret[0].(dto.TopupWalletResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Topup indicates an expected call of Topup.
func (mr *MockWalletServiceMockRecorder) Topup(ctx, userID, amount, idempotencyKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Topup", reflect.TypeOf((*MockWalletService)(nil).Topup), ctx, userID, amount, idempotencyKey)
}
