// Code generated by MockGen. DO NOT EDIT.
// Source: services/commerce/internal/delivery/handlers/handlers.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/go-park-mail-ru/2026_1_VKernelTeam/clover/services/commerce/internal/domain/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockCart is a mock of Cart interface.
type MockCart struct {
	ctrl     *gomock.Controller
	recorder *MockCartMockRecorder
}

// MockCartMockRecorder is the mock recorder for MockCart.
type MockCartMockRecorder struct {
	mock *MockCart
}

// NewMockCart creates a new mock instance.
func NewMockCart(ctrl *gomock.Controller) *MockCart {
	mock := &MockCart{ctrl: ctrl}
	mock.recorder = &MockCartMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCart) EXPECT() *MockCartMockRecorder {
	return m.recorder
}

// AddToCart mocks base method.
func (m *MockCart) AddToCart(ctx context.Context, userID, productID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddToCart", ctx, userID, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddToCart indicates an expected call of AddToCart.
func (mr *MockCartMockRecorder) AddToCart(ctx, userID, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToCart", reflect.TypeOf((*MockCart)(nil).AddToCart), ctx, userID, productID)
}

// GetCart mocks base method.
func (m *MockCart) GetCart(ctx context.Context, userID int64) (*dto.CartResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCart", ctx, userID)
	ret0, _ := ret[0].(*dto.CartResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCart indicates an expected call of GetCart.
func (mr *MockCartMockRecorder) GetCart(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCart", reflect.TypeOf((*MockCart)(nil).GetCart), ctx, userID)
}

// RemoveFromCart mocks base method.
func (m *MockCart) RemoveFromCart(ctx context.Context, userID, productID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFromCart", ctx, userID, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFromCart indicates an expected call of RemoveFromCart.
func (mr *MockCartMockRecorder) RemoveFromCart(ctx, userID, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFromCart", reflect.TypeOf((*MockCart)(nil).RemoveFromCart), ctx, userID, productID)
}

// MockChat is a mock of Chat interface.
type MockChat struct {
	ctrl     *gomock.Controller
	recorder *MockChatMockRecorder
}

// MockChatMockRecorder is the mock recorder for MockChat.
type MockChatMockRecorder struct {
	mock *MockChat
}

// NewMockChat creates a new mock instance.
func NewMockChat(ctrl *gomock.Controller) *MockChat {
	mock := &MockChat{ctrl: ctrl}
	mock.recorder = &MockChatMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChat) EXPECT() *MockChatMockRecorder {
	return m.recorder
}

// ConfirmPurchase mocks base method.
func (m *MockChat) ConfirmPurchase(ctx context.Context, chatID, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmPurchase", ctx, chatID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmPurchase indicates an expected call of ConfirmPurchase.
func (mr *MockChatMockRecorder) ConfirmPurchase(ctx, chatID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmPurchase", reflect.TypeOf((*MockChat)(nil).ConfirmPurchase), ctx, chatID, userID)
}

// CreateOrderRequest mocks base method.
func (m *MockChat) CreateOrderRequest(ctx context.Context, adID, buyerID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrderRequest", ctx, adID, buyerID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrderRequest indicates an expected call of CreateOrderRequest.
func (mr *MockChatMockRecorder) CreateOrderRequest(ctx, adID, buyerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrderRequest", reflect.TypeOf((*MockChat)(nil).CreateOrderRequest), ctx, adID, buyerID)
}

// GetAllChats mocks base method.
func (m *MockChat) GetAllChats(ctx context.Context, userID int64) (dto.ChatListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllChats", ctx, userID)
	ret0, _ := ret[0].(dto.ChatListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllChats indicates an expected call of GetAllChats.
func (mr *MockChatMockRecorder) GetAllChats(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllChats", reflect.TypeOf((*MockChat)(nil).GetAllChats), ctx, userID)
}

// GetChat mocks base method.
func (m *MockChat) GetChat(ctx context.Context, chatID, userID int64) (dto.ChatDetailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChat", ctx, chatID, userID)
	ret0, _ := ret[0].(dto.ChatDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChat indicates an expected call of GetChat.
func (mr *MockChatMockRecorder) GetChat(ctx, chatID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChat", reflect.TypeOf((*MockChat)(nil).GetChat), ctx, chatID, userID)
}
