// Code generated by MockGen. DO NOT EDIT.
// Source: promotion.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/go-park-mail-ru/2026_1_VKernelTeam/clover/services/commerce/internal/domain/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockPromotionService is a mock of PromotionService interface.
type MockPromotionService struct {
	ctrl     *gomock.Controller
	recorder *MockPromotionServiceMockRecorder
}

// MockPromotionServiceMockRecorder is the mock recorder for MockPromotionService.
type MockPromotionServiceMockRecorder struct {
	mock *MockPromotionService
}

// NewMockPromotionService creates a new mock instance.
func NewMockPromotionService(ctrl *gomock.Controller) *MockPromotionService {
	mock := &MockPromotionService{ctrl: ctrl}
	mock.recorder = &MockPromotionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPromotionService) EXPECT() *MockPromotionServiceMockRecorder {
	return m.recorder
}

// GetPlans mocks base method.
func (m *MockPromotionService) GetPlans(ctx context.Context) ([]dto.PromotionPlanResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlans", ctx)
	ret0, _ := ret[0].([]dto.PromotionPlanResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlans indicates an expected call of GetPlans.
func (mr *MockPromotionServiceMockRecorder) GetPlans(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlans", reflect.TypeOf((*MockPromotionService)(nil).GetPlans), ctx)
}

// ListActiveByAd mocks base method.
func (m *MockPromotionService) ListActiveByAd(ctx context.Context, productID int64) ([]dto.PromotionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveByAd", ctx, productID)
	ret0, _ := ret[0].([]dto.PromotionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveByAd indicates an expected call of ListActiveByAd.
func (mr *MockPromotionServiceMockRecorder) ListActiveByAd(ctx, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveByAd", reflect.TypeOf((*MockPromotionService)(nil).ListActiveByAd), ctx, productID)
}

// ListByUser mocks base method.
func (m *MockPromotionService) ListByUser(ctx context.Context, userID, cursor int64, limit int) (dto.PromotionListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID, cursor, limit)
	ret0, _ := ret[0].(dto.PromotionListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockPromotionServiceMockRecorder) ListByUser(ctx, userID, cursor, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockPromotionService)(nil).ListByUser), ctx, userID, cursor, limit)
}

// Purchase mocks base method.
func (m *MockPromotionService) Purchase(ctx context.Context, userID, productID int64, planCode, idempotencyKey string) (dto.PurchasePromotionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Purchase", ctx, userID, productID, planCode, idempotencyKey)
	ret0, _ := ret[0].(dto.PurchasePromotionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Purchase indicates an expected call of Purchase.
func (mr *MockPromotionServiceMockRecorder) Purchase(ctx, userID, productID, planCode, idempotencyKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Purchase", reflect.TypeOf((*MockPromotionService)(nil).Purchase), ctx, userID, productID, planCode, idempotencyKey)
}
