// Code generated by MockGen. DO NOT EDIT.
// Source: support_message.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2026_1_VKernelTeam/clover/internal/domain/models"
	gomock "github.com/golang/mock/gomock"
)

// MockTicketStorage is a mock of TicketStorage interface.
type MockTicketStorage struct {
	ctrl     *gomock.Controller
	recorder *MockTicketStorageMockRecorder
}

// MockTicketStorageMockRecorder is the mock recorder for MockTicketStorage.
type MockTicketStorageMockRecorder struct {
	mock *MockTicketStorage
}

// NewMockTicketStorage creates a new mock instance.
func NewMockTicketStorage(ctrl *gomock.Controller) *MockTicketStorage {
	mock := &MockTicketStorage{ctrl: ctrl}
	mock.recorder = &MockTicketStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTicketStorage) EXPECT() *MockTicketStorageMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockTicketStorage) GetByID(ctx context.Context, id int64) (*models.SupportTicket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.SupportTicket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTicketStorageMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTicketStorage)(nil).GetByID), ctx, id)
}

// MockMessageStorage is a mock of MessageStorage interface.
type MockMessageStorage struct {
	ctrl     *gomock.Controller
	recorder *MockMessageStorageMockRecorder
}

// MockMessageStorageMockRecorder is the mock recorder for MockMessageStorage.
type MockMessageStorageMockRecorder struct {
	mock *MockMessageStorage
}

// NewMockMessageStorage creates a new mock instance.
func NewMockMessageStorage(ctrl *gomock.Controller) *MockMessageStorage {
	mock := &MockMessageStorage{ctrl: ctrl}
	mock.recorder = &MockMessageStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageStorage) EXPECT() *MockMessageStorageMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMessageStorage) Create(ctx context.Context, msg *models.SupportMessage) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, msg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMessageStorageMockRecorder) Create(ctx, msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMessageStorage)(nil).Create), ctx, msg)
}

// GetByTicketID mocks base method.
func (m *MockMessageStorage) GetByTicketID(ctx context.Context, ticketID int64) ([]models.SupportMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTicketID", ctx, ticketID)
	ret0, _ := ret[0].([]models.SupportMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTicketID indicates an expected call of GetByTicketID.
func (mr *MockMessageStorageMockRecorder) GetByTicketID(ctx, ticketID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTicketID", reflect.TypeOf((*MockMessageStorage)(nil).GetByTicketID), ctx, ticketID)
}

// MockRoleProvider is a mock of RoleProvider interface.
type MockRoleProvider struct {
	ctrl     *gomock.Controller
	recorder *MockRoleProviderMockRecorder
}

// MockRoleProviderMockRecorder is the mock recorder for MockRoleProvider.
type MockRoleProviderMockRecorder struct {
	mock *MockRoleProvider
}

// NewMockRoleProvider creates a new mock instance.
func NewMockRoleProvider(ctrl *gomock.Controller) *MockRoleProvider {
	mock := &MockRoleProvider{ctrl: ctrl}
	mock.recorder = &MockRoleProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleProvider) EXPECT() *MockRoleProviderMockRecorder {
	return m.recorder
}

// GetUserRole mocks base method.
func (m *MockRoleProvider) GetUserRole(ctx context.Context, userID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRole", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRole indicates an expected call of GetUserRole.
func (mr *MockRoleProviderMockRecorder) GetUserRole(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRole", reflect.TypeOf((*MockRoleProvider)(nil).GetUserRole), ctx, userID)
}
