// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/auth/auth.go

// Package mock_auth is a generated GoMock package.
package mock_auth

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/go-park-mail-ru/2026_1_VKernelTeam/clover/internal/domain/models"
	gomock "github.com/golang/mock/gomock"
)

// MockTokenRevoker is a mock of TokenRevoker interface.
type MockTokenRevoker struct {
	ctrl     *gomock.Controller
	recorder *MockTokenRevokerMockRecorder
}

// MockTokenRevokerMockRecorder is the mock recorder for MockTokenRevoker.
type MockTokenRevokerMockRecorder struct {
	mock *MockTokenRevoker
}

// NewMockTokenRevoker creates a new mock instance.
func NewMockTokenRevoker(ctrl *gomock.Controller) *MockTokenRevoker {
	mock := &MockTokenRevoker{ctrl: ctrl}
	mock.recorder = &MockTokenRevokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenRevoker) EXPECT() *MockTokenRevokerMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockTokenRevoker) Add(jti string, exp time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Add", jti, exp)
}

// Add indicates an expected call of Add.
func (mr *MockTokenRevokerMockRecorder) Add(jti, exp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockTokenRevoker)(nil).Add), jti, exp)
}

// MockUserProviderSaver is a mock of UserProviderSaver interface.
type MockUserProviderSaver struct {
	ctrl     *gomock.Controller
	recorder *MockUserProviderSaverMockRecorder
}

// MockUserProviderSaverMockRecorder is the mock recorder for MockUserProviderSaver.
type MockUserProviderSaverMockRecorder struct {
	mock *MockUserProviderSaver
}

// NewMockUserProviderSaver creates a new mock instance.
func NewMockUserProviderSaver(ctrl *gomock.Controller) *MockUserProviderSaver {
	mock := &MockUserProviderSaver{ctrl: ctrl}
	mock.recorder = &MockUserProviderSaverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserProviderSaver) EXPECT() *MockUserProviderSaverMockRecorder {
	return m.recorder
}

// IsAdmin mocks base method.
func (m *MockUserProviderSaver) IsAdmin(ctx context.Context, userID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAdmin", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAdmin indicates an expected call of IsAdmin.
func (mr *MockUserProviderSaverMockRecorder) IsAdmin(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAdmin", reflect.TypeOf((*MockUserProviderSaver)(nil).IsAdmin), ctx, userID)
}

// SaveUser mocks base method.
func (m *MockUserProviderSaver) SaveUser(ctx context.Context, email string, passHash []byte, name string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUser", ctx, email, passHash, name)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveUser indicates an expected call of SaveUser.
func (mr *MockUserProviderSaverMockRecorder) SaveUser(ctx, email, passHash, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUser", reflect.TypeOf((*MockUserProviderSaver)(nil).SaveUser), ctx, email, passHash, name)
}

// User mocks base method.
func (m *MockUserProviderSaver) User(ctx context.Context, email string) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "User", ctx, email)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// User indicates an expected call of User.
func (mr *MockUserProviderSaverMockRecorder) User(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "User", reflect.TypeOf((*MockUserProviderSaver)(nil).User), ctx, email)
}

// UserByID mocks base method.
func (m *MockUserProviderSaver) UserByID(ctx context.Context, userID int64) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserByID", ctx, userID)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserByID indicates an expected call of UserByID.
func (mr *MockUserProviderSaverMockRecorder) UserByID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserByID", reflect.TypeOf((*MockUserProviderSaver)(nil).UserByID), ctx, userID)
}
