// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson452fbfDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesSupportInternalDomainModels(in *jlexer.Lexer, out *SupportMessage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "ticket_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TicketID = int64(in.Int64())
			}
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int64(in.Int64())
			}
		case "text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Text = string(in.String())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson452fbfEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesSupportInternalDomainModels(out *jwriter.Writer, in SupportMessage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"ticket_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.TicketID))
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.UserID))
	}
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix)
		out.String(string(in.Text))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SupportMessage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson452fbfEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesSupportInternalDomainModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SupportMessage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson452fbfEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesSupportInternalDomainModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SupportMessage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson452fbfDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesSupportInternalDomainModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SupportMessage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson452fbfDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesSupportInternalDomainModels(l, v)
}
