// Code generated by MockGen. DO NOT EDIT.
// Source: promotion.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/go-park-mail-ru/2026_1_VKernelTeam/clover/services/commerce/internal/domain/models"
	gomock "github.com/golang/mock/gomock"
	pgx "github.com/jackc/pgx/v5"
)

// MockTxRunner is a mock of TxRunner interface.
type MockTxRunner struct {
	ctrl     *gomock.Controller
	recorder *MockTxRunnerMockRecorder
}

// MockTxRunnerMockRecorder is the mock recorder for MockTxRunner.
type MockTxRunnerMockRecorder struct {
	mock *MockTxRunner
}

// NewMockTxRunner creates a new mock instance.
func NewMockTxRunner(ctrl *gomock.Controller) *MockTxRunner {
	mock := &MockTxRunner{ctrl: ctrl}
	mock.recorder = &MockTxRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxRunner) EXPECT() *MockTxRunnerMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockTxRunner) Begin(ctx context.Context) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockTxRunnerMockRecorder) Begin(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockTxRunner)(nil).Begin), ctx)
}

// MockPlanRepo is a mock of PlanRepo interface.
type MockPlanRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPlanRepoMockRecorder
}

// MockPlanRepoMockRecorder is the mock recorder for MockPlanRepo.
type MockPlanRepoMockRecorder struct {
	mock *MockPlanRepo
}

// NewMockPlanRepo creates a new mock instance.
func NewMockPlanRepo(ctrl *gomock.Controller) *MockPlanRepo {
	mock := &MockPlanRepo{ctrl: ctrl}
	mock.recorder = &MockPlanRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlanRepo) EXPECT() *MockPlanRepoMockRecorder {
	return m.recorder
}

// GetActivePlans mocks base method.
func (m *MockPlanRepo) GetActivePlans(ctx context.Context) ([]models.PromotionPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivePlans", ctx)
	ret0, _ := ret[0].([]models.PromotionPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActivePlans indicates an expected call of GetActivePlans.
func (mr *MockPlanRepoMockRecorder) GetActivePlans(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivePlans", reflect.TypeOf((*MockPlanRepo)(nil).GetActivePlans), ctx)
}

// GetByCode mocks base method.
func (m *MockPlanRepo) GetByCode(ctx context.Context, code string) (models.PromotionPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, code)
	ret0, _ := ret[0].(models.PromotionPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockPlanRepoMockRecorder) GetByCode(ctx, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockPlanRepo)(nil).GetByCode), ctx, code)
}

// GetByID mocks base method.
func (m *MockPlanRepo) GetByID(ctx context.Context, id int64) (models.PromotionPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(models.PromotionPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPlanRepoMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPlanRepo)(nil).GetByID), ctx, id)
}

// MockPromotionRepo is a mock of PromotionRepo interface.
type MockPromotionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPromotionRepoMockRecorder
}

// MockPromotionRepoMockRecorder is the mock recorder for MockPromotionRepo.
type MockPromotionRepoMockRecorder struct {
	mock *MockPromotionRepo
}

// NewMockPromotionRepo creates a new mock instance.
func NewMockPromotionRepo(ctrl *gomock.Controller) *MockPromotionRepo {
	mock := &MockPromotionRepo{ctrl: ctrl}
	mock.recorder = &MockPromotionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPromotionRepo) EXPECT() *MockPromotionRepoMockRecorder {
	return m.recorder
}

// GetActiveByAd mocks base method.
func (m *MockPromotionRepo) GetActiveByAd(ctx context.Context, productID int64) ([]models.Promotion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveByAd", ctx, productID)
	ret0, _ := ret[0].([]models.Promotion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveByAd indicates an expected call of GetActiveByAd.
func (mr *MockPromotionRepoMockRecorder) GetActiveByAd(ctx, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveByAd", reflect.TypeOf((*MockPromotionRepo)(nil).GetActiveByAd), ctx, productID)
}

// GetByID mocks base method.
func (m *MockPromotionRepo) GetByID(ctx context.Context, id int64) (models.Promotion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(models.Promotion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPromotionRepoMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPromotionRepo)(nil).GetByID), ctx, id)
}

// InsertTx mocks base method.
func (m *MockPromotionRepo) InsertTx(ctx context.Context, tx pgx.Tx, productID, userID, planID int64, kind string, expiresAt time.Time, pricePaid int64) (models.Promotion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertTx", ctx, tx, productID, userID, planID, kind, expiresAt, pricePaid)
	ret0, _ := ret[0].(models.Promotion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertTx indicates an expected call of InsertTx.
func (mr *MockPromotionRepoMockRecorder) InsertTx(ctx, tx, productID, userID, planID, kind, expiresAt, pricePaid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertTx", reflect.TypeOf((*MockPromotionRepo)(nil).InsertTx), ctx, tx, productID, userID, planID, kind, expiresAt, pricePaid)
}

// ListByUser mocks base method.
func (m *MockPromotionRepo) ListByUser(ctx context.Context, userID, cursor int64, limit int) ([]models.Promotion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID, cursor, limit)
	ret0, _ := ret[0].([]models.Promotion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockPromotionRepoMockRecorder) ListByUser(ctx, userID, cursor, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockPromotionRepo)(nil).ListByUser), ctx, userID, cursor, limit)
}

// MaxActiveExpiresTx mocks base method.
func (m *MockPromotionRepo) MaxActiveExpiresTx(ctx context.Context, tx pgx.Tx, productID int64, kind string) (time.Time, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxActiveExpiresTx", ctx, tx, productID, kind)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// MaxActiveExpiresTx indicates an expected call of MaxActiveExpiresTx.
func (mr *MockPromotionRepoMockRecorder) MaxActiveExpiresTx(ctx, tx, productID, kind interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxActiveExpiresTx", reflect.TypeOf((*MockPromotionRepo)(nil).MaxActiveExpiresTx), ctx, tx, productID, kind)
}

// MockWalletRepo is a mock of WalletRepo interface.
type MockWalletRepo struct {
	ctrl     *gomock.Controller
	recorder *MockWalletRepoMockRecorder
}

// MockWalletRepoMockRecorder is the mock recorder for MockWalletRepo.
type MockWalletRepoMockRecorder struct {
	mock *MockWalletRepo
}

// NewMockWalletRepo creates a new mock instance.
func NewMockWalletRepo(ctrl *gomock.Controller) *MockWalletRepo {
	mock := &MockWalletRepo{ctrl: ctrl}
	mock.recorder = &MockWalletRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletRepo) EXPECT() *MockWalletRepoMockRecorder {
	return m.recorder
}

// DecrementBalanceTx mocks base method.
func (m *MockWalletRepo) DecrementBalanceTx(ctx context.Context, tx pgx.Tx, userID, amount int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementBalanceTx", ctx, tx, userID, amount)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecrementBalanceTx indicates an expected call of DecrementBalanceTx.
func (mr *MockWalletRepoMockRecorder) DecrementBalanceTx(ctx, tx, userID, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementBalanceTx", reflect.TypeOf((*MockWalletRepo)(nil).DecrementBalanceTx), ctx, tx, userID, amount)
}

// Get mocks base method.
func (m *MockWalletRepo) Get(ctx context.Context, userID int64) (models.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID)
	ret0, _ := ret[0].(models.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockWalletRepoMockRecorder) Get(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockWalletRepo)(nil).Get), ctx, userID)
}

// GetForUpdateTx mocks base method.
func (m *MockWalletRepo) GetForUpdateTx(ctx context.Context, tx pgx.Tx, userID int64) (models.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForUpdateTx", ctx, tx, userID)
	ret0, _ := ret[0].(models.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetForUpdateTx indicates an expected call of GetForUpdateTx.
func (mr *MockWalletRepoMockRecorder) GetForUpdateTx(ctx, tx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForUpdateTx", reflect.TypeOf((*MockWalletRepo)(nil).GetForUpdateTx), ctx, tx, userID)
}

// GetTransactionByIdempotencyKey mocks base method.
func (m *MockWalletRepo) GetTransactionByIdempotencyKey(ctx context.Context, key string) (models.WalletTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionByIdempotencyKey", ctx, key)
	ret0, _ := ret[0].(models.WalletTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionByIdempotencyKey indicates an expected call of GetTransactionByIdempotencyKey.
func (mr *MockWalletRepoMockRecorder) GetTransactionByIdempotencyKey(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionByIdempotencyKey", reflect.TypeOf((*MockWalletRepo)(nil).GetTransactionByIdempotencyKey), ctx, key)
}

// InsertTransactionTx mocks base method.
func (m *MockWalletRepo) InsertTransactionTx(ctx context.Context, tx pgx.Tx, userID, amount int64, txType string, referenceID *int64, idempotencyKey *string) (models.WalletTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertTransactionTx", ctx, tx, userID, amount, txType, referenceID, idempotencyKey)
	ret0, _ := ret[0].(models.WalletTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertTransactionTx indicates an expected call of InsertTransactionTx.
func (mr *MockWalletRepoMockRecorder) InsertTransactionTx(ctx, tx, userID, amount, txType, referenceID, idempotencyKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertTransactionTx", reflect.TypeOf((*MockWalletRepo)(nil).InsertTransactionTx), ctx, tx, userID, amount, txType, referenceID, idempotencyKey)
}

// MockPlanCache is a mock of PlanCache interface.
type MockPlanCache struct {
	ctrl     *gomock.Controller
	recorder *MockPlanCacheMockRecorder
}

// MockPlanCacheMockRecorder is the mock recorder for MockPlanCache.
type MockPlanCacheMockRecorder struct {
	mock *MockPlanCache
}

// NewMockPlanCache creates a new mock instance.
func NewMockPlanCache(ctrl *gomock.Controller) *MockPlanCache {
	mock := &MockPlanCache{ctrl: ctrl}
	mock.recorder = &MockPlanCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlanCache) EXPECT() *MockPlanCacheMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockPlanCache) Get(ctx context.Context) ([]models.PromotionPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx)
	ret0, _ := ret[0].([]models.PromotionPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPlanCacheMockRecorder) Get(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPlanCache)(nil).Get), ctx)
}

// Set mocks base method.
func (m *MockPlanCache) Set(ctx context.Context, plans []models.PromotionPlan) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, plans)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockPlanCacheMockRecorder) Set(ctx, plans interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockPlanCache)(nil).Set), ctx, plans)
}

// MockAdsProvider is a mock of AdsProvider interface.
type MockAdsProvider struct {
	ctrl     *gomock.Controller
	recorder *MockAdsProviderMockRecorder
}

// MockAdsProviderMockRecorder is the mock recorder for MockAdsProvider.
type MockAdsProviderMockRecorder struct {
	mock *MockAdsProvider
}

// NewMockAdsProvider creates a new mock instance.
func NewMockAdsProvider(ctrl *gomock.Controller) *MockAdsProvider {
	mock := &MockAdsProvider{ctrl: ctrl}
	mock.recorder = &MockAdsProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdsProvider) EXPECT() *MockAdsProviderMockRecorder {
	return m.recorder
}

// GetAdByID mocks base method.
func (m *MockAdsProvider) GetAdByID(ctx context.Context, id int64) (models.Ad, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdByID", ctx, id)
	ret0, _ := ret[0].(models.Ad)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdByID indicates an expected call of GetAdByID.
func (mr *MockAdsProviderMockRecorder) GetAdByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdByID", reflect.TypeOf((*MockAdsProvider)(nil).GetAdByID), ctx, id)
}
