// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson452fbfDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesSupportInternalDomainDto(in *jlexer.Lexer, out *TicketStatusResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "updated_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson452fbfEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesSupportInternalDomainDto(out *jwriter.Writer, in TicketStatusResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TicketStatusResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson452fbfEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesSupportInternalDomainDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TicketStatusResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson452fbfEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesSupportInternalDomainDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TicketStatusResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson452fbfDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesSupportInternalDomainDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TicketStatusResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson452fbfDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesSupportInternalDomainDto(l, v)
}
func easyjson452fbfDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesSupportInternalDomainDto1(in *jlexer.Lexer, out *StatsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "total":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Total = int(in.Int())
			}
		case "by_status":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.ByStatus = make(map[string]int)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 int
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = int(in.Int())
					}
					(out.ByStatus)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		case "by_category":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.ByCategory = make(map[string]int)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v2 int
					if in.IsNull() {
						in.Skip()
					} else {
						v2 = int(in.Int())
					}
					(out.ByCategory)[key] = v2
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson452fbfEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesSupportInternalDomainDto1(out *jwriter.Writer, in StatsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"total\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Total))
	}
	{
		const prefix string = ",\"by_status\":"
		out.RawString(prefix)
		if in.ByStatus == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v3First := true
			for v3Name, v3Value := range in.ByStatus {
				if v3First {
					v3First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v3Name))
				out.RawByte(':')
				out.Int(int(v3Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"by_category\":"
		out.RawString(prefix)
		if in.ByCategory == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v4First := true
			for v4Name, v4Value := range in.ByCategory {
				if v4First {
					v4First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v4Name))
				out.RawByte(':')
				out.Int(int(v4Value))
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v StatsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson452fbfEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesSupportInternalDomainDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v StatsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson452fbfEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesSupportInternalDomainDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *StatsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson452fbfDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesSupportInternalDomainDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *StatsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson452fbfDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesSupportInternalDomainDto1(l, v)
}
func easyjson452fbfDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesSupportInternalDomainDto2(in *jlexer.Lexer, out *SendMessageRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Text = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson452fbfEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesSupportInternalDomainDto2(out *jwriter.Writer, in SendMessageRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix[1:])
		out.String(string(in.Text))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SendMessageRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson452fbfEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesSupportInternalDomainDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SendMessageRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson452fbfEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesSupportInternalDomainDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SendMessageRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson452fbfDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesSupportInternalDomainDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SendMessageRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson452fbfDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesSupportInternalDomainDto2(l, v)
}
func easyjson452fbfDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesSupportInternalDomainDto3(in *jlexer.Lexer, out *MessageResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "ticket_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TicketID = int64(in.Int64())
			}
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int64(in.Int64())
			}
		case "text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Text = string(in.String())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson452fbfEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesSupportInternalDomainDto3(out *jwriter.Writer, in MessageResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"ticket_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.TicketID))
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.UserID))
	}
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix)
		out.String(string(in.Text))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MessageResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson452fbfEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesSupportInternalDomainDto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MessageResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson452fbfEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesSupportInternalDomainDto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MessageResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson452fbfDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesSupportInternalDomainDto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MessageResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson452fbfDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesSupportInternalDomainDto3(l, v)
}
func easyjson452fbfDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesSupportInternalDomainDto4(in *jlexer.Lexer, out *ChangeStatusRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson452fbfEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesSupportInternalDomainDto4(out *jwriter.Writer, in ChangeStatusRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.String(string(in.Status))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ChangeStatusRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson452fbfEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesSupportInternalDomainDto4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ChangeStatusRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson452fbfEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesSupportInternalDomainDto4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ChangeStatusRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson452fbfDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesSupportInternalDomainDto4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ChangeStatusRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson452fbfDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesSupportInternalDomainDto4(l, v)
}
