// Code generated by MockGen. DO NOT EDIT.
// Source: ads.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	multipart "mime/multipart"
	reflect "reflect"

	config "github.com/go-park-mail-ru/2026_1_VKernelTeam/clover/internal/config"
	dto "github.com/go-park-mail-ru/2026_1_VKernelTeam/clover/internal/domain/dto"
	models "github.com/go-park-mail-ru/2026_1_VKernelTeam/clover/internal/domain/models"
	gomock "github.com/golang/mock/gomock"
)

// MockAdsProvider is a mock of AdsProvider interface.
type MockAdsProvider struct {
	ctrl     *gomock.Controller
	recorder *MockAdsProviderMockRecorder
}

// MockAdsProviderMockRecorder is the mock recorder for MockAdsProvider.
type MockAdsProviderMockRecorder struct {
	mock *MockAdsProvider
}

// NewMockAdsProvider creates a new mock instance.
func NewMockAdsProvider(ctrl *gomock.Controller) *MockAdsProvider {
	mock := &MockAdsProvider{ctrl: ctrl}
	mock.recorder = &MockAdsProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdsProvider) EXPECT() *MockAdsProviderMockRecorder {
	return m.recorder
}

// AddFavorite mocks base method.
func (m *MockAdsProvider) AddFavorite(ctx context.Context, userID, adID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFavorite", ctx, userID, adID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFavorite indicates an expected call of AddFavorite.
func (mr *MockAdsProviderMockRecorder) AddFavorite(ctx, userID, adID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFavorite", reflect.TypeOf((*MockAdsProvider)(nil).AddFavorite), ctx, userID, adID)
}

// AddProductImages mocks base method.
func (m *MockAdsProvider) AddProductImages(ctx context.Context, adID int64, photos []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProductImages", ctx, adID, photos)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddProductImages indicates an expected call of AddProductImages.
func (mr *MockAdsProviderMockRecorder) AddProductImages(ctx, adID, photos interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProductImages", reflect.TypeOf((*MockAdsProvider)(nil).AddProductImages), ctx, adID, photos)
}

// CloseAd mocks base method.
func (m *MockAdsProvider) CloseAd(ctx context.Context, id, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseAd", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseAd indicates an expected call of CloseAd.
func (mr *MockAdsProviderMockRecorder) CloseAd(ctx, id, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseAd", reflect.TypeOf((*MockAdsProvider)(nil).CloseAd), ctx, id, userID)
}

// CreateAd mocks base method.
func (m *MockAdsProvider) CreateAd(ctx context.Context, req *dto.CreateAdRequest) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAd", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAd indicates an expected call of CreateAd.
func (mr *MockAdsProviderMockRecorder) CreateAd(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAd", reflect.TypeOf((*MockAdsProvider)(nil).CreateAd), ctx, req)
}

// DeleteAd mocks base method.
func (m *MockAdsProvider) DeleteAd(ctx context.Context, id, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAd", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAd indicates an expected call of DeleteAd.
func (mr *MockAdsProviderMockRecorder) DeleteAd(ctx, id, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAd", reflect.TypeOf((*MockAdsProvider)(nil).DeleteAd), ctx, id, userID)
}

// DeleteProductImages mocks base method.
func (m *MockAdsProvider) DeleteProductImages(ctx context.Context, adID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProductImages", ctx, adID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProductImages indicates an expected call of DeleteProductImages.
func (mr *MockAdsProviderMockRecorder) DeleteProductImages(ctx, adID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProductImages", reflect.TypeOf((*MockAdsProvider)(nil).DeleteProductImages), ctx, adID)
}

// GetAdByID mocks base method.
func (m *MockAdsProvider) GetAdByID(ctx context.Context, id int64) (models.Ad, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdByID", ctx, id)
	ret0, _ := ret[0].(models.Ad)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdByID indicates an expected call of GetAdByID.
func (mr *MockAdsProviderMockRecorder) GetAdByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdByID", reflect.TypeOf((*MockAdsProvider)(nil).GetAdByID), ctx, id)
}

// GetAdsByUserID mocks base method.
func (m *MockAdsProvider) GetAdsByUserID(ctx context.Context, userID int64) ([]models.Ad, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdsByUserID", ctx, userID)
	ret0, _ := ret[0].([]models.Ad)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdsByUserID indicates an expected call of GetAdsByUserID.
func (mr *MockAdsProviderMockRecorder) GetAdsByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdsByUserID", reflect.TypeOf((*MockAdsProvider)(nil).GetAdsByUserID), ctx, userID)
}

// GetAllAds mocks base method.
func (m *MockAdsProvider) GetAllAds(ctx context.Context) ([]models.Ad, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllAds", ctx)
	ret0, _ := ret[0].([]models.Ad)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllAds indicates an expected call of GetAllAds.
func (mr *MockAdsProviderMockRecorder) GetAllAds(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllAds", reflect.TypeOf((*MockAdsProvider)(nil).GetAllAds), ctx)
}

// GetCategoryCharacteristics mocks base method.
func (m *MockAdsProvider) GetCategoryCharacteristics(ctx context.Context, categoryID int64) ([]models.CategoryCharacteristic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryCharacteristics", ctx, categoryID)
	ret0, _ := ret[0].([]models.CategoryCharacteristic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryCharacteristics indicates an expected call of GetCategoryCharacteristics.
func (mr *MockAdsProviderMockRecorder) GetCategoryCharacteristics(ctx, categoryID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryCharacteristics", reflect.TypeOf((*MockAdsProvider)(nil).GetCategoryCharacteristics), ctx, categoryID)
}

// GetUserFavorites mocks base method.
func (m *MockAdsProvider) GetUserFavorites(ctx context.Context, userID int64) ([]models.Ad, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserFavorites", ctx, userID)
	ret0, _ := ret[0].([]models.Ad)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserFavorites indicates an expected call of GetUserFavorites.
func (mr *MockAdsProviderMockRecorder) GetUserFavorites(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserFavorites", reflect.TypeOf((*MockAdsProvider)(nil).GetUserFavorites), ctx, userID)
}

// RemoveFavorite mocks base method.
func (m *MockAdsProvider) RemoveFavorite(ctx context.Context, userID, adID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFavorite", ctx, userID, adID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFavorite indicates an expected call of RemoveFavorite.
func (mr *MockAdsProviderMockRecorder) RemoveFavorite(ctx, userID, adID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFavorite", reflect.TypeOf((*MockAdsProvider)(nil).RemoveFavorite), ctx, userID, adID)
}

// SearchAds mocks base method.
func (m *MockAdsProvider) SearchAds(ctx context.Context, variants []string, categoryID int64, cfg config.SearchConfig) ([]models.Ad, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchAds", ctx, variants, categoryID, cfg)
	ret0, _ := ret[0].([]models.Ad)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchAds indicates an expected call of SearchAds.
func (mr *MockAdsProviderMockRecorder) SearchAds(ctx, variants, categoryID, cfg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchAds", reflect.TypeOf((*MockAdsProvider)(nil).SearchAds), ctx, variants, categoryID, cfg)
}

// SetProductCharacteristics mocks base method.
func (m *MockAdsProvider) SetProductCharacteristics(ctx context.Context, productID int64, inputs []dto.CharacteristicInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProductCharacteristics", ctx, productID, inputs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetProductCharacteristics indicates an expected call of SetProductCharacteristics.
func (mr *MockAdsProviderMockRecorder) SetProductCharacteristics(ctx, productID, inputs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProductCharacteristics", reflect.TypeOf((*MockAdsProvider)(nil).SetProductCharacteristics), ctx, productID, inputs)
}

// SetProductCustomCharacteristics mocks base method.
func (m *MockAdsProvider) SetProductCustomCharacteristics(ctx context.Context, productID int64, inputs []dto.CustomCharacteristicInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProductCustomCharacteristics", ctx, productID, inputs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetProductCustomCharacteristics indicates an expected call of SetProductCustomCharacteristics.
func (mr *MockAdsProviderMockRecorder) SetProductCustomCharacteristics(ctx, productID, inputs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProductCustomCharacteristics", reflect.TypeOf((*MockAdsProvider)(nil).SetProductCustomCharacteristics), ctx, productID, inputs)
}

// UpdateAd mocks base method.
func (m *MockAdsProvider) UpdateAd(ctx context.Context, req *dto.UpdateAdRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAd", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAd indicates an expected call of UpdateAd.
func (mr *MockAdsProviderMockRecorder) UpdateAd(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAd", reflect.TypeOf((*MockAdsProvider)(nil).UpdateAd), ctx, req)
}

// MockFileStorage is a mock of FileStorage interface.
type MockFileStorage struct {
	ctrl     *gomock.Controller
	recorder *MockFileStorageMockRecorder
}

// MockFileStorageMockRecorder is the mock recorder for MockFileStorage.
type MockFileStorageMockRecorder struct {
	mock *MockFileStorage
}

// NewMockFileStorage creates a new mock instance.
func NewMockFileStorage(ctrl *gomock.Controller) *MockFileStorage {
	mock := &MockFileStorage{ctrl: ctrl}
	mock.recorder = &MockFileStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileStorage) EXPECT() *MockFileStorageMockRecorder {
	return m.recorder
}

// DeleteFile mocks base method.
func (m *MockFileStorage) DeleteFile(ctx context.Context, fileURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", ctx, fileURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockFileStorageMockRecorder) DeleteFile(ctx, fileURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockFileStorage)(nil).DeleteFile), ctx, fileURL)
}

// UploadFile mocks base method.
func (m *MockFileStorage) UploadFile(ctx context.Context, file multipart.File, folder, extension string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", ctx, file, folder, extension)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockFileStorageMockRecorder) UploadFile(ctx, file, folder, extension interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockFileStorage)(nil).UploadFile), ctx, file, folder, extension)
}
