// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson22b96abDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainModels(in *jlexer.Lexer, out *WalletTransaction) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "ID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "UserID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int64(in.Int64())
			}
		case "Amount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Amount = int64(in.Int64())
			}
		case "Type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "ReferenceID":
			if in.IsNull() {
				in.Skip()
				out.ReferenceID = nil
			} else {
				if out.ReferenceID == nil {
					out.ReferenceID = new(int64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.ReferenceID = int64(in.Int64())
				}
			}
		case "IdempotencyKey":
			if in.IsNull() {
				in.Skip()
				out.IdempotencyKey = nil
			} else {
				if out.IdempotencyKey == nil {
					out.IdempotencyKey = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.IdempotencyKey = string(in.String())
				}
			}
		case "CreatedAt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson22b96abEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainModels(out *jwriter.Writer, in WalletTransaction) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ID\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"UserID\":"
		out.RawString(prefix)
		out.Int64(int64(in.UserID))
	}
	{
		const prefix string = ",\"Amount\":"
		out.RawString(prefix)
		out.Int64(int64(in.Amount))
	}
	{
		const prefix string = ",\"Type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"ReferenceID\":"
		out.RawString(prefix)
		if in.ReferenceID == nil {
			out.RawString("null")
		} else {
			out.Int64(int64(*in.ReferenceID))
		}
	}
	{
		const prefix string = ",\"IdempotencyKey\":"
		out.RawString(prefix)
		if in.IdempotencyKey == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.IdempotencyKey))
		}
	}
	{
		const prefix string = ",\"CreatedAt\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WalletTransaction) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson22b96abEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WalletTransaction) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson22b96abEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WalletTransaction) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson22b96abDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WalletTransaction) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson22b96abDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainModels(l, v)
}
func easyjson22b96abDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainModels1(in *jlexer.Lexer, out *Wallet) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "UserID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int64(in.Int64())
			}
		case "Balance":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Balance = int64(in.Int64())
			}
		case "UpdatedAt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson22b96abEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainModels1(out *jwriter.Writer, in Wallet) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"UserID\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.UserID))
	}
	{
		const prefix string = ",\"Balance\":"
		out.RawString(prefix)
		out.Int64(int64(in.Balance))
	}
	{
		const prefix string = ",\"UpdatedAt\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Wallet) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson22b96abEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Wallet) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson22b96abEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Wallet) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson22b96abDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Wallet) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson22b96abDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainModels1(l, v)
}
