// Code generated by MockGen. DO NOT EDIT.
// Source: handlers.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	dto "github.com/go-park-mail-ru/2026_1_VKernelTeam/clover/internal/domain/dto"
	models "github.com/go-park-mail-ru/2026_1_VKernelTeam/clover/internal/domain/models"
	gomock "github.com/golang/mock/gomock"
)

// MockAds is a mock of Ads interface.
type MockAds struct {
	ctrl     *gomock.Controller
	recorder *MockAdsMockRecorder
}

// MockAdsMockRecorder is the mock recorder for MockAds.
type MockAdsMockRecorder struct {
	mock *MockAds
}

// NewMockAds creates a new mock instance.
func NewMockAds(ctrl *gomock.Controller) *MockAds {
	mock := &MockAds{ctrl: ctrl}
	mock.recorder = &MockAdsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAds) EXPECT() *MockAdsMockRecorder {
	return m.recorder
}

// CreateAd mocks base method.
func (m *MockAds) CreateAd(ctx context.Context, req *dto.CreateAdRequest) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAd", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAd indicates an expected call of CreateAd.
func (mr *MockAdsMockRecorder) CreateAd(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAd", reflect.TypeOf((*MockAds)(nil).CreateAd), ctx, req)
}

// GetAllAds mocks base method.
func (m *MockAds) GetAllAds(ctx context.Context) ([]models.Ad, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllAds", ctx)
	ret0, _ := ret[0].([]models.Ad)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllAds indicates an expected call of GetAllAds.
func (mr *MockAdsMockRecorder) GetAllAds(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllAds", reflect.TypeOf((*MockAds)(nil).GetAllAds), ctx)
}

// MockAuth is a mock of Auth interface.
type MockAuth struct {
	ctrl     *gomock.Controller
	recorder *MockAuthMockRecorder
}

// MockAuthMockRecorder is the mock recorder for MockAuth.
type MockAuthMockRecorder struct {
	mock *MockAuth
}

// NewMockAuth creates a new mock instance.
func NewMockAuth(ctrl *gomock.Controller) *MockAuth {
	mock := &MockAuth{ctrl: ctrl}
	mock.recorder = &MockAuthMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuth) EXPECT() *MockAuthMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockAuth) Login(ctx context.Context, email, password string) (string, string, models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(models.User)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// Login indicates an expected call of Login.
func (mr *MockAuthMockRecorder) Login(ctx, email, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuth)(nil).Login), ctx, email, password)
}

// Logout mocks base method.
func (m *MockAuth) Logout(ctx context.Context, jti string, exp time.Time, refreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, jti, exp, refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthMockRecorder) Logout(ctx, jti, exp, refreshToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuth)(nil).Logout), ctx, jti, exp, refreshToken)
}

// Refresh mocks base method.
func (m *MockAuth) Refresh(ctx context.Context, refreshToken string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, refreshToken)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Refresh indicates an expected call of Refresh.
func (mr *MockAuthMockRecorder) Refresh(ctx, refreshToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockAuth)(nil).Refresh), ctx, refreshToken)
}

// RegisterNewUser mocks base method.
func (m *MockAuth) RegisterNewUser(ctx context.Context, email, password, name string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterNewUser", ctx, email, password, name)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterNewUser indicates an expected call of RegisterNewUser.
func (mr *MockAuthMockRecorder) RegisterNewUser(ctx, email, password, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterNewUser", reflect.TypeOf((*MockAuth)(nil).RegisterNewUser), ctx, email, password, name)
}

// ValidateTokenAndGetUser mocks base method.
func (m *MockAuth) ValidateTokenAndGetUser(ctx context.Context, tokenString string) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateTokenAndGetUser", ctx, tokenString)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateTokenAndGetUser indicates an expected call of ValidateTokenAndGetUser.
func (mr *MockAuthMockRecorder) ValidateTokenAndGetUser(ctx, tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateTokenAndGetUser", reflect.TypeOf((*MockAuth)(nil).ValidateTokenAndGetUser), ctx, tokenString)
}
