// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson63cbde9bDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCatalogInternalDomainModels(in *jlexer.Lexer, out *Ad) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "seller_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SellerID = int64(in.Int64())
			}
		case "category_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CategoryID = int64(in.Int64())
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		case "price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = int64(in.Int64())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "views_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ViewsCount = int64(in.Int64())
			}
		case "favorites_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FavoritesCount = int64(in.Int64())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "updated_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		case "deleted_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.DeletedAt).UnmarshalJSON(data))
				}
			}
		case "photos":
			if in.IsNull() {
				in.Skip()
				out.Photos = nil
			} else {
				in.Delim('[')
				if out.Photos == nil {
					if !in.IsDelim(']') {
						out.Photos = make([]string, 0, 4)
					} else {
						out.Photos = []string{}
					}
				} else {
					out.Photos = (out.Photos)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					out.Photos = append(out.Photos, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "location":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Location = string(in.String())
			}
		case "lat":
			if in.IsNull() {
				in.Skip()
				out.Lat = nil
			} else {
				if out.Lat == nil {
					out.Lat = new(float64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Lat = float64(in.Float64())
				}
			}
		case "lon":
			if in.IsNull() {
				in.Skip()
				out.Lon = nil
			} else {
				if out.Lon == nil {
					out.Lon = new(float64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Lon = float64(in.Float64())
				}
			}
		case "is_boosted":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsBoosted = bool(in.Bool())
			}
		case "is_highlighted":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsHighlighted = bool(in.Bool())
			}
		case "category_characteristics":
			if in.IsNull() {
				in.Skip()
				out.CategoryCharacteristics = nil
			} else {
				in.Delim('[')
				if out.CategoryCharacteristics == nil {
					if !in.IsDelim(']') {
						out.CategoryCharacteristics = make([]ProductCharacteristic, 0, 2)
					} else {
						out.CategoryCharacteristics = []ProductCharacteristic{}
					}
				} else {
					out.CategoryCharacteristics = (out.CategoryCharacteristics)[:0]
				}
				for !in.IsDelim(']') {
					var v2 ProductCharacteristic
					if in.IsNull() {
						in.Skip()
					} else {
						(v2).UnmarshalEasyJSON(in)
					}
					out.CategoryCharacteristics = append(out.CategoryCharacteristics, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "custom_characteristics":
			if in.IsNull() {
				in.Skip()
				out.CustomCharacteristics = nil
			} else {
				in.Delim('[')
				if out.CustomCharacteristics == nil {
					if !in.IsDelim(']') {
						out.CustomCharacteristics = make([]ProductCustomCharacteristic, 0, 2)
					} else {
						out.CustomCharacteristics = []ProductCustomCharacteristic{}
					}
				} else {
					out.CustomCharacteristics = (out.CustomCharacteristics)[:0]
				}
				for !in.IsDelim(']') {
					var v3 ProductCustomCharacteristic
					if in.IsNull() {
						in.Skip()
					} else {
						(v3).UnmarshalEasyJSON(in)
					}
					out.CustomCharacteristics = append(out.CustomCharacteristics, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson63cbde9bEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCatalogInternalDomainModels(out *jwriter.Writer, in Ad) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"seller_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.SellerID))
	}
	{
		const prefix string = ",\"category_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.CategoryID))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Int64(int64(in.Price))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"views_count\":"
		out.RawString(prefix)
		out.Int64(int64(in.ViewsCount))
	}
	{
		const prefix string = ",\"favorites_count\":"
		out.RawString(prefix)
		out.Int64(int64(in.FavoritesCount))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"deleted_at\":"
		out.RawString(prefix)
		out.Raw((in.DeletedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"photos\":"
		out.RawString(prefix)
		if in.Photos == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v4, v5 := range in.Photos {
				if v4 > 0 {
					out.RawByte(',')
				}
				out.String(string(v5))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"location\":"
		out.RawString(prefix)
		out.String(string(in.Location))
	}
	if in.Lat != nil {
		const prefix string = ",\"lat\":"
		out.RawString(prefix)
		out.Float64(float64(*in.Lat))
	}
	if in.Lon != nil {
		const prefix string = ",\"lon\":"
		out.RawString(prefix)
		out.Float64(float64(*in.Lon))
	}
	{
		const prefix string = ",\"is_boosted\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsBoosted))
	}
	{
		const prefix string = ",\"is_highlighted\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsHighlighted))
	}
	{
		const prefix string = ",\"category_characteristics\":"
		out.RawString(prefix)
		if in.CategoryCharacteristics == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v6, v7 := range in.CategoryCharacteristics {
				if v6 > 0 {
					out.RawByte(',')
				}
				(v7).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"custom_characteristics\":"
		out.RawString(prefix)
		if in.CustomCharacteristics == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.CustomCharacteristics {
				if v8 > 0 {
					out.RawByte(',')
				}
				(v9).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Ad) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson63cbde9bEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCatalogInternalDomainModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Ad) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson63cbde9bEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCatalogInternalDomainModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Ad) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson63cbde9bDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCatalogInternalDomainModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Ad) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson63cbde9bDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCatalogInternalDomainModels(l, v)
}
