// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson75ee7adfDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCatalogInternalDomainModels(in *jlexer.Lexer, out *ProductCustomCharacteristic) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson75ee7adfEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCatalogInternalDomainModels(out *jwriter.Writer, in ProductCustomCharacteristic) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		out.String(string(in.Value))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ProductCustomCharacteristic) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson75ee7adfEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCatalogInternalDomainModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ProductCustomCharacteristic) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson75ee7adfEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCatalogInternalDomainModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ProductCustomCharacteristic) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson75ee7adfDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCatalogInternalDomainModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ProductCustomCharacteristic) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson75ee7adfDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCatalogInternalDomainModels(l, v)
}
func easyjson75ee7adfDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCatalogInternalDomainModels1(in *jlexer.Lexer, out *ProductCharacteristic) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson75ee7adfEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCatalogInternalDomainModels1(out *jwriter.Writer, in ProductCharacteristic) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		out.String(string(in.Value))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ProductCharacteristic) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson75ee7adfEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCatalogInternalDomainModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ProductCharacteristic) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson75ee7adfEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCatalogInternalDomainModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ProductCharacteristic) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson75ee7adfDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCatalogInternalDomainModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ProductCharacteristic) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson75ee7adfDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCatalogInternalDomainModels1(l, v)
}
func easyjson75ee7adfDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCatalogInternalDomainModels2(in *jlexer.Lexer, out *CategoryCharacteristic) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "category_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CategoryID = int64(in.Int64())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "allowed_values":
			if in.IsNull() {
				in.Skip()
				out.AllowedValues = nil
			} else {
				in.Delim('[')
				if out.AllowedValues == nil {
					if !in.IsDelim(']') {
						out.AllowedValues = make([]string, 0, 4)
					} else {
						out.AllowedValues = []string{}
					}
				} else {
					out.AllowedValues = (out.AllowedValues)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					out.AllowedValues = append(out.AllowedValues, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "sort_order":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SortOrder = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson75ee7adfEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCatalogInternalDomainModels2(out *jwriter.Writer, in CategoryCharacteristic) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"category_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.CategoryID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"allowed_values\":"
		out.RawString(prefix)
		if in.AllowedValues == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.AllowedValues {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"sort_order\":"
		out.RawString(prefix)
		out.Int(int(in.SortOrder))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CategoryCharacteristic) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson75ee7adfEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCatalogInternalDomainModels2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CategoryCharacteristic) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson75ee7adfEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCatalogInternalDomainModels2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CategoryCharacteristic) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson75ee7adfDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCatalogInternalDomainModels2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CategoryCharacteristic) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson75ee7adfDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCatalogInternalDomainModels2(l, v)
}
