// Code generated by MockGen. DO NOT EDIT.
// Source: handlers.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	multipart "mime/multipart"
	reflect "reflect"

	dto "github.com/go-park-mail-ru/2026_1_VKernelTeam/clover/services/catalog/internal/domain/dto"
	models "github.com/go-park-mail-ru/2026_1_VKernelTeam/clover/services/catalog/internal/domain/models"
	gomock "github.com/golang/mock/gomock"
)

// MockAds is a mock of Ads interface.
type MockAds struct {
	ctrl     *gomock.Controller
	recorder *MockAdsMockRecorder
}

// MockAdsMockRecorder is the mock recorder for MockAds.
type MockAdsMockRecorder struct {
	mock *MockAds
}

// NewMockAds creates a new mock instance.
func NewMockAds(ctrl *gomock.Controller) *MockAds {
	mock := &MockAds{ctrl: ctrl}
	mock.recorder = &MockAdsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAds) EXPECT() *MockAdsMockRecorder {
	return m.recorder
}

// AddFavorite mocks base method.
func (m *MockAds) AddFavorite(ctx context.Context, userID, adID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFavorite", ctx, userID, adID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFavorite indicates an expected call of AddFavorite.
func (mr *MockAdsMockRecorder) AddFavorite(ctx, userID, adID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFavorite", reflect.TypeOf((*MockAds)(nil).AddFavorite), ctx, userID, adID)
}

// AdminDeleteAd mocks base method.
func (m *MockAds) AdminDeleteAd(ctx context.Context, adID, adminID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminDeleteAd", ctx, adID, adminID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdminDeleteAd indicates an expected call of AdminDeleteAd.
func (mr *MockAdsMockRecorder) AdminDeleteAd(ctx, adID, adminID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminDeleteAd", reflect.TypeOf((*MockAds)(nil).AdminDeleteAd), ctx, adID, adminID)
}

// ApproveAd mocks base method.
func (m *MockAds) ApproveAd(ctx context.Context, adID, adminID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveAd", ctx, adID, adminID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveAd indicates an expected call of ApproveAd.
func (mr *MockAdsMockRecorder) ApproveAd(ctx, adID, adminID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveAd", reflect.TypeOf((*MockAds)(nil).ApproveAd), ctx, adID, adminID)
}

// CloseAd mocks base method.
func (m *MockAds) CloseAd(ctx context.Context, id, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseAd", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseAd indicates an expected call of CloseAd.
func (mr *MockAdsMockRecorder) CloseAd(ctx, id, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseAd", reflect.TypeOf((*MockAds)(nil).CloseAd), ctx, id, userID)
}

// CreateAd mocks base method.
func (m *MockAds) CreateAd(ctx context.Context, req *dto.CreateAdRequest) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAd", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAd indicates an expected call of CreateAd.
func (mr *MockAdsMockRecorder) CreateAd(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAd", reflect.TypeOf((*MockAds)(nil).CreateAd), ctx, req)
}

// DeleteAd mocks base method.
func (m *MockAds) DeleteAd(ctx context.Context, id, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAd", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAd indicates an expected call of DeleteAd.
func (mr *MockAdsMockRecorder) DeleteAd(ctx, id, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAd", reflect.TypeOf((*MockAds)(nil).DeleteAd), ctx, id, userID)
}

// GetAdByID mocks base method.
func (m *MockAds) GetAdByID(ctx context.Context, id int64) (models.Ad, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdByID", ctx, id)
	ret0, _ := ret[0].(models.Ad)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdByID indicates an expected call of GetAdByID.
func (mr *MockAdsMockRecorder) GetAdByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdByID", reflect.TypeOf((*MockAds)(nil).GetAdByID), ctx, id)
}

// GetAdsByUserID mocks base method.
func (m *MockAds) GetAdsByUserID(ctx context.Context, userID int64) ([]models.Ad, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdsByUserID", ctx, userID)
	ret0, _ := ret[0].([]models.Ad)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdsByUserID indicates an expected call of GetAdsByUserID.
func (mr *MockAdsMockRecorder) GetAdsByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdsByUserID", reflect.TypeOf((*MockAds)(nil).GetAdsByUserID), ctx, userID)
}

// GetAllAds mocks base method.
func (m *MockAds) GetAllAds(ctx context.Context, limit, offset int32) ([]models.Ad, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllAds", ctx, limit, offset)
	ret0, _ := ret[0].([]models.Ad)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllAds indicates an expected call of GetAllAds.
func (mr *MockAdsMockRecorder) GetAllAds(ctx, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllAds", reflect.TypeOf((*MockAds)(nil).GetAllAds), ctx, limit, offset)
}

// GetCategoryCharacteristics mocks base method.
func (m *MockAds) GetCategoryCharacteristics(ctx context.Context, categoryID int64) ([]models.CategoryCharacteristic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryCharacteristics", ctx, categoryID)
	ret0, _ := ret[0].([]models.CategoryCharacteristic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryCharacteristics indicates an expected call of GetCategoryCharacteristics.
func (mr *MockAdsMockRecorder) GetCategoryCharacteristics(ctx, categoryID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryCharacteristics", reflect.TypeOf((*MockAds)(nil).GetCategoryCharacteristics), ctx, categoryID)
}

// GetModerationQueue mocks base method.
func (m *MockAds) GetModerationQueue(ctx context.Context) ([]models.Ad, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModerationQueue", ctx)
	ret0, _ := ret[0].([]models.Ad)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModerationQueue indicates an expected call of GetModerationQueue.
func (mr *MockAdsMockRecorder) GetModerationQueue(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModerationQueue", reflect.TypeOf((*MockAds)(nil).GetModerationQueue), ctx)
}

// GetPriceHistory mocks base method.
func (m *MockAds) GetPriceHistory(ctx context.Context, adID int64) ([]models.PricePoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPriceHistory", ctx, adID)
	ret0, _ := ret[0].([]models.PricePoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPriceHistory indicates an expected call of GetPriceHistory.
func (mr *MockAdsMockRecorder) GetPriceHistory(ctx, adID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPriceHistory", reflect.TypeOf((*MockAds)(nil).GetPriceHistory), ctx, adID)
}

// GetUserAdsByStatus mocks base method.
func (m *MockAds) GetUserAdsByStatus(ctx context.Context, userID int64, status string) ([]models.Ad, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAdsByStatus", ctx, userID, status)
	ret0, _ := ret[0].([]models.Ad)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAdsByStatus indicates an expected call of GetUserAdsByStatus.
func (mr *MockAdsMockRecorder) GetUserAdsByStatus(ctx, userID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAdsByStatus", reflect.TypeOf((*MockAds)(nil).GetUserAdsByStatus), ctx, userID, status)
}

// GetUserFavorites mocks base method.
func (m *MockAds) GetUserFavorites(ctx context.Context, userID int64) ([]models.Ad, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserFavorites", ctx, userID)
	ret0, _ := ret[0].([]models.Ad)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserFavorites indicates an expected call of GetUserFavorites.
func (mr *MockAdsMockRecorder) GetUserFavorites(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserFavorites", reflect.TypeOf((*MockAds)(nil).GetUserFavorites), ctx, userID)
}

// IsModerationEnabled mocks base method.
func (m *MockAds) IsModerationEnabled(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsModerationEnabled", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsModerationEnabled indicates an expected call of IsModerationEnabled.
func (mr *MockAdsMockRecorder) IsModerationEnabled(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsModerationEnabled", reflect.TypeOf((*MockAds)(nil).IsModerationEnabled), ctx)
}

// RejectAd mocks base method.
func (m *MockAds) RejectAd(ctx context.Context, adID, adminID int64, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RejectAd", ctx, adID, adminID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// RejectAd indicates an expected call of RejectAd.
func (mr *MockAdsMockRecorder) RejectAd(ctx, adID, adminID, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectAd", reflect.TypeOf((*MockAds)(nil).RejectAd), ctx, adID, adminID, reason)
}

// RemoveFavorite mocks base method.
func (m *MockAds) RemoveFavorite(ctx context.Context, userID, adID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFavorite", ctx, userID, adID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFavorite indicates an expected call of RemoveFavorite.
func (mr *MockAdsMockRecorder) RemoveFavorite(ctx, userID, adID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFavorite", reflect.TypeOf((*MockAds)(nil).RemoveFavorite), ctx, userID, adID)
}

// SearchAds mocks base method.
func (m *MockAds) SearchAds(ctx context.Context, query string, categoryID int64) ([]models.Ad, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchAds", ctx, query, categoryID)
	ret0, _ := ret[0].([]models.Ad)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchAds indicates an expected call of SearchAds.
func (mr *MockAdsMockRecorder) SearchAds(ctx, query, categoryID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchAds", reflect.TypeOf((*MockAds)(nil).SearchAds), ctx, query, categoryID)
}

// SetModerationEnabled mocks base method.
func (m *MockAds) SetModerationEnabled(ctx context.Context, enabled bool, adminID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetModerationEnabled", ctx, enabled, adminID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetModerationEnabled indicates an expected call of SetModerationEnabled.
func (mr *MockAdsMockRecorder) SetModerationEnabled(ctx, enabled, adminID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetModerationEnabled", reflect.TypeOf((*MockAds)(nil).SetModerationEnabled), ctx, enabled, adminID)
}

// UpdateAd mocks base method.
func (m *MockAds) UpdateAd(ctx context.Context, req *dto.UpdateAdRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAd", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAd indicates an expected call of UpdateAd.
func (mr *MockAdsMockRecorder) UpdateAd(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAd", reflect.TypeOf((*MockAds)(nil).UpdateAd), ctx, req)
}

// UploadAdPhotos mocks base method.
func (m *MockAds) UploadAdPhotos(ctx context.Context, files []multipart.File, filenames []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadAdPhotos", ctx, files, filenames)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadAdPhotos indicates an expected call of UploadAdPhotos.
func (mr *MockAdsMockRecorder) UploadAdPhotos(ctx, files, filenames interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadAdPhotos", reflect.TypeOf((*MockAds)(nil).UploadAdPhotos), ctx, files, filenames)
}

// MockViews is a mock of Views interface.
type MockViews struct {
	ctrl     *gomock.Controller
	recorder *MockViewsMockRecorder
}

// MockViewsMockRecorder is the mock recorder for MockViews.
type MockViewsMockRecorder struct {
	mock *MockViews
}

// NewMockViews creates a new mock instance.
func NewMockViews(ctrl *gomock.Controller) *MockViews {
	mock := &MockViews{ctrl: ctrl}
	mock.recorder = &MockViewsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockViews) EXPECT() *MockViewsMockRecorder {
	return m.recorder
}

// RecordView mocks base method.
func (m *MockViews) RecordView(ctx context.Context, productID int64, userID *int64, deviceID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordView", ctx, productID, userID, deviceID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordView indicates an expected call of RecordView.
func (mr *MockViewsMockRecorder) RecordView(ctx, productID, userID, deviceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordView", reflect.TypeOf((*MockViews)(nil).RecordView), ctx, productID, userID, deviceID)
}
