// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/views/views.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/go-park-mail-ru/2026_1_VKernelTeam/clover/internal/domain/models"
	view "github.com/go-park-mail-ru/2026_1_VKernelTeam/clover/internal/repository/view"
	gomock "github.com/golang/mock/gomock"
)

// MockViewCache is a mock of ViewCache interface.
type MockViewCache struct {
	ctrl     *gomock.Controller
	recorder *MockViewCacheMockRecorder
}

// MockViewCacheMockRecorder is the mock recorder for MockViewCache.
type MockViewCacheMockRecorder struct {
	mock *MockViewCache
}

// NewMockViewCache creates a new mock instance.
func NewMockViewCache(ctrl *gomock.Controller) *MockViewCache {
	mock := &MockViewCache{ctrl: ctrl}
	mock.recorder = &MockViewCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockViewCache) EXPECT() *MockViewCacheMockRecorder {
	return m.recorder
}

// CheckAndSetDedup mocks base method.
func (m *MockViewCache) CheckAndSetDedup(ctx context.Context, productID int64, identifier string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAndSetDedup", ctx, productID, identifier)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAndSetDedup indicates an expected call of CheckAndSetDedup.
func (mr *MockViewCacheMockRecorder) CheckAndSetDedup(ctx, productID, identifier interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAndSetDedup", reflect.TypeOf((*MockViewCache)(nil).CheckAndSetDedup), ctx, productID, identifier)
}

// GetCount mocks base method.
func (m *MockViewCache) GetCount(ctx context.Context, productID int64) (int64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCount", ctx, productID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCount indicates an expected call of GetCount.
func (mr *MockViewCacheMockRecorder) GetCount(ctx, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCount", reflect.TypeOf((*MockViewCache)(nil).GetCount), ctx, productID)
}

// IncrementCount mocks base method.
func (m *MockViewCache) IncrementCount(ctx context.Context, productID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementCount", ctx, productID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementCount indicates an expected call of IncrementCount.
func (mr *MockViewCacheMockRecorder) IncrementCount(ctx, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementCount", reflect.TypeOf((*MockViewCache)(nil).IncrementCount), ctx, productID)
}

// SetCount mocks base method.
func (m *MockViewCache) SetCount(ctx context.Context, productID, count int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCount", ctx, productID, count)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCount indicates an expected call of SetCount.
func (mr *MockViewCacheMockRecorder) SetCount(ctx, productID, count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCount", reflect.TypeOf((*MockViewCache)(nil).SetCount), ctx, productID, count)
}

// MockViewProducer is a mock of ViewProducer interface.
type MockViewProducer struct {
	ctrl     *gomock.Controller
	recorder *MockViewProducerMockRecorder
}

// MockViewProducerMockRecorder is the mock recorder for MockViewProducer.
type MockViewProducerMockRecorder struct {
	mock *MockViewProducer
}

// NewMockViewProducer creates a new mock instance.
func NewMockViewProducer(ctrl *gomock.Controller) *MockViewProducer {
	mock := &MockViewProducer{ctrl: ctrl}
	mock.recorder = &MockViewProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockViewProducer) EXPECT() *MockViewProducerMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockViewProducer) Publish(ctx context.Context, event models.ViewEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockViewProducerMockRecorder) Publish(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockViewProducer)(nil).Publish), ctx, event)
}

// MockViewConsumer is a mock of ViewConsumer interface.
type MockViewConsumer struct {
	ctrl     *gomock.Controller
	recorder *MockViewConsumerMockRecorder
}

// MockViewConsumerMockRecorder is the mock recorder for MockViewConsumer.
type MockViewConsumerMockRecorder struct {
	mock *MockViewConsumer
}

// NewMockViewConsumer creates a new mock instance.
func NewMockViewConsumer(ctrl *gomock.Controller) *MockViewConsumer {
	mock := &MockViewConsumer{ctrl: ctrl}
	mock.recorder = &MockViewConsumerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockViewConsumer) EXPECT() *MockViewConsumerMockRecorder {
	return m.recorder
}

// Ack mocks base method.
func (m *MockViewConsumer) Ack(ctx context.Context, messageIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ack", ctx, messageIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ack indicates an expected call of Ack.
func (mr *MockViewConsumerMockRecorder) Ack(ctx, messageIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ack", reflect.TypeOf((*MockViewConsumer)(nil).Ack), ctx, messageIDs)
}

// ReadBatch mocks base method.
func (m *MockViewConsumer) ReadBatch(ctx context.Context, count int64, blockTimeout time.Duration) ([]models.ViewEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadBatch", ctx, count, blockTimeout)
	ret0, _ := ret[0].([]models.ViewEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadBatch indicates an expected call of ReadBatch.
func (mr *MockViewConsumerMockRecorder) ReadBatch(ctx, count, blockTimeout interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadBatch", reflect.TypeOf((*MockViewConsumer)(nil).ReadBatch), ctx, count, blockTimeout)
}

// MockViewStorage is a mock of ViewStorage interface.
type MockViewStorage struct {
	ctrl     *gomock.Controller
	recorder *MockViewStorageMockRecorder
}

// MockViewStorageMockRecorder is the mock recorder for MockViewStorage.
type MockViewStorageMockRecorder struct {
	mock *MockViewStorage
}

// NewMockViewStorage creates a new mock instance.
func NewMockViewStorage(ctrl *gomock.Controller) *MockViewStorage {
	mock := &MockViewStorage{ctrl: ctrl}
	mock.recorder = &MockViewStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockViewStorage) EXPECT() *MockViewStorageMockRecorder {
	return m.recorder
}

// BatchInsertViews mocks base method.
func (m *MockViewStorage) BatchInsertViews(ctx context.Context, events []view.InsertEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchInsertViews", ctx, events)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchInsertViews indicates an expected call of BatchInsertViews.
func (mr *MockViewStorageMockRecorder) BatchInsertViews(ctx, events interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchInsertViews", reflect.TypeOf((*MockViewStorage)(nil).BatchInsertViews), ctx, events)
}

// GetViewsCount mocks base method.
func (m *MockViewStorage) GetViewsCount(ctx context.Context, productID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetViewsCount", ctx, productID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetViewsCount indicates an expected call of GetViewsCount.
func (mr *MockViewStorageMockRecorder) GetViewsCount(ctx, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetViewsCount", reflect.TypeOf((*MockViewStorage)(nil).GetViewsCount), ctx, productID)
}
