// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonDdb0949aDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto(in *jlexer.Lexer, out *CartResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "items":
			if in.IsNull() {
				in.Skip()
				out.Items = nil
			} else {
				in.Delim('[')
				if out.Items == nil {
					if !in.IsDelim(']') {
						out.Items = make([]CartItemResponse, 0, 0)
					} else {
						out.Items = []CartItemResponse{}
					}
				} else {
					out.Items = (out.Items)[:0]
				}
				for !in.IsDelim(']') {
					var v1 CartItemResponse
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Items = append(out.Items, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "total_price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TotalPrice = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonDdb0949aEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto(out *jwriter.Writer, in CartResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"items\":"
		out.RawString(prefix[1:])
		if in.Items == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Items {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"total_price\":"
		out.RawString(prefix)
		out.Int64(int64(in.TotalPrice))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CartResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonDdb0949aEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CartResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonDdb0949aEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CartResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDdb0949aDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CartResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDdb0949aDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto(l, v)
}
func easyjsonDdb0949aDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto1(in *jlexer.Lexer, out *CartItemResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "product_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ProductID = int64(in.Int64())
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "price":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Price = int64(in.Int64())
			}
		case "seller_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SellerID = int64(in.Int64())
			}
		case "seller_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SellerName = string(in.String())
			}
		case "image_path":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ImagePath = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonDdb0949aEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto1(out *jwriter.Writer, in CartItemResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"product_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ProductID))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.Int64(int64(in.Price))
	}
	{
		const prefix string = ",\"seller_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.SellerID))
	}
	{
		const prefix string = ",\"seller_name\":"
		out.RawString(prefix)
		out.String(string(in.SellerName))
	}
	if in.ImagePath != "" {
		const prefix string = ",\"image_path\":"
		out.RawString(prefix)
		out.String(string(in.ImagePath))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CartItemResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonDdb0949aEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CartItemResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonDdb0949aEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CartItemResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDdb0949aDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CartItemResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDdb0949aDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto1(l, v)
}
func easyjsonDdb0949aDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto2(in *jlexer.Lexer, out *AddToCartRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "product_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ProductID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonDdb0949aEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto2(out *jwriter.Writer, in AddToCartRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"product_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ProductID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AddToCartRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonDdb0949aEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AddToCartRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonDdb0949aEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AddToCartRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDdb0949aDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AddToCartRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDdb0949aDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto2(l, v)
}
