// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson2f096870DecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto(in *jlexer.Lexer, out *UpdateReviewRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "rating":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Rating = int(in.Int())
			}
		case "content":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Content = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2f096870EncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto(out *jwriter.Writer, in UpdateReviewRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"rating\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Rating))
	}
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		out.String(string(in.Content))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpdateReviewRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2f096870EncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpdateReviewRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2f096870EncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpdateReviewRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2f096870DecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpdateReviewRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2f096870DecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto(l, v)
}
func easyjson2f096870DecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto1(in *jlexer.Lexer, out *ReviewSummaryResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "average":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Average = float64(in.Float64())
			}
		case "total":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Total = int(in.Int())
			}
		case "distribution":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Distribution = make(map[int]int)
				for !in.IsDelim('}') {
					key := int(in.IntStr())
					in.WantColon()
					var v1 int
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = int(in.Int())
					}
					(out.Distribution)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2f096870EncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto1(out *jwriter.Writer, in ReviewSummaryResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"average\":"
		out.RawString(prefix[1:])
		out.Float64(float64(in.Average))
	}
	{
		const prefix string = ",\"total\":"
		out.RawString(prefix)
		out.Int(int(in.Total))
	}
	{
		const prefix string = ",\"distribution\":"
		out.RawString(prefix)
		if in.Distribution == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v2First := true
			for v2Name, v2Value := range in.Distribution {
				if v2First {
					v2First = false
				} else {
					out.RawByte(',')
				}
				out.IntStr(int(v2Name))
				out.RawByte(':')
				out.Int(int(v2Value))
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ReviewSummaryResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2f096870EncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ReviewSummaryResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2f096870EncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ReviewSummaryResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2f096870DecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ReviewSummaryResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2f096870DecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto1(l, v)
}
func easyjson2f096870DecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto2(in *jlexer.Lexer, out *ReviewResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "sender":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Sender).UnmarshalEasyJSON(in)
			}
		case "receiver_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ReceiverID = int64(in.Int64())
			}
		case "product":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Product).UnmarshalEasyJSON(in)
			}
		case "rating":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Rating = int(in.Int())
			}
		case "content":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Content = string(in.String())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "updated_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2f096870EncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto2(out *jwriter.Writer, in ReviewResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"sender\":"
		out.RawString(prefix)
		(in.Sender).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"receiver_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.ReceiverID))
	}
	{
		const prefix string = ",\"product\":"
		out.RawString(prefix)
		(in.Product).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"rating\":"
		out.RawString(prefix)
		out.Int(int(in.Rating))
	}
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		out.String(string(in.Content))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ReviewResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2f096870EncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ReviewResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2f096870EncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ReviewResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2f096870DecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ReviewResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2f096870DecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto2(l, v)
}
func easyjson2f096870DecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto3(in *jlexer.Lexer, out *ReviewListResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "reviews":
			if in.IsNull() {
				in.Skip()
				out.Reviews = nil
			} else {
				in.Delim('[')
				if out.Reviews == nil {
					if !in.IsDelim(']') {
						out.Reviews = make([]ReviewResponse, 0, 0)
					} else {
						out.Reviews = []ReviewResponse{}
					}
				} else {
					out.Reviews = (out.Reviews)[:0]
				}
				for !in.IsDelim(']') {
					var v3 ReviewResponse
					if in.IsNull() {
						in.Skip()
					} else {
						(v3).UnmarshalEasyJSON(in)
					}
					out.Reviews = append(out.Reviews, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "next_cursor":
			if in.IsNull() {
				in.Skip()
				out.NextCursor = nil
			} else {
				if out.NextCursor == nil {
					out.NextCursor = new(int64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.NextCursor = int64(in.Int64())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2f096870EncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto3(out *jwriter.Writer, in ReviewListResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"reviews\":"
		out.RawString(prefix[1:])
		if in.Reviews == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v4, v5 := range in.Reviews {
				if v4 > 0 {
					out.RawByte(',')
				}
				(v5).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if in.NextCursor != nil {
		const prefix string = ",\"next_cursor\":"
		out.RawString(prefix)
		out.Int64(int64(*in.NextCursor))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ReviewListResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2f096870EncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ReviewListResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2f096870EncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ReviewListResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2f096870DecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ReviewListResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2f096870DecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto3(l, v)
}
func easyjson2f096870DecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto4(in *jlexer.Lexer, out *CreateReviewResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "review":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Review).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2f096870EncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto4(out *jwriter.Writer, in CreateReviewResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"review\":"
		out.RawString(prefix[1:])
		(in.Review).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateReviewResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2f096870EncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateReviewResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2f096870EncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateReviewResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2f096870DecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateReviewResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2f096870DecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto4(l, v)
}
func easyjson2f096870DecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto5(in *jlexer.Lexer, out *CreateReviewRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "receiver_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ReceiverID = int64(in.Int64())
			}
		case "product_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ProductID = int64(in.Int64())
			}
		case "rating":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Rating = int(in.Int())
			}
		case "content":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Content = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2f096870EncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto5(out *jwriter.Writer, in CreateReviewRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"receiver_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ReceiverID))
	}
	{
		const prefix string = ",\"product_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.ProductID))
	}
	{
		const prefix string = ",\"rating\":"
		out.RawString(prefix)
		out.Int(int(in.Rating))
	}
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		out.String(string(in.Content))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateReviewRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2f096870EncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateReviewRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2f096870EncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateReviewRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2f096870DecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateReviewRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2f096870DecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto5(l, v)
}
