// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson22b96abDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto(in *jlexer.Lexer, out *WalletTransactionResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "amount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Amount = int64(in.Int64())
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "reference_id":
			if in.IsNull() {
				in.Skip()
				out.ReferenceID = nil
			} else {
				if out.ReferenceID == nil {
					out.ReferenceID = new(int64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.ReferenceID = int64(in.Int64())
				}
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson22b96abEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto(out *jwriter.Writer, in WalletTransactionResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix)
		out.Int64(int64(in.Amount))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	if in.ReferenceID != nil {
		const prefix string = ",\"reference_id\":"
		out.RawString(prefix)
		out.Int64(int64(*in.ReferenceID))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WalletTransactionResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson22b96abEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WalletTransactionResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson22b96abEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WalletTransactionResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson22b96abDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WalletTransactionResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson22b96abDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto(l, v)
}
func easyjson22b96abDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto1(in *jlexer.Lexer, out *WalletTransactionListResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "items":
			if in.IsNull() {
				in.Skip()
				out.Items = nil
			} else {
				in.Delim('[')
				if out.Items == nil {
					if !in.IsDelim(']') {
						out.Items = make([]WalletTransactionResponse, 0, 1)
					} else {
						out.Items = []WalletTransactionResponse{}
					}
				} else {
					out.Items = (out.Items)[:0]
				}
				for !in.IsDelim(']') {
					var v1 WalletTransactionResponse
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Items = append(out.Items, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "next_cursor":
			if in.IsNull() {
				in.Skip()
				out.NextCursor = nil
			} else {
				if out.NextCursor == nil {
					out.NextCursor = new(int64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.NextCursor = int64(in.Int64())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson22b96abEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto1(out *jwriter.Writer, in WalletTransactionListResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"items\":"
		out.RawString(prefix[1:])
		if in.Items == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Items {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if in.NextCursor != nil {
		const prefix string = ",\"next_cursor\":"
		out.RawString(prefix)
		out.Int64(int64(*in.NextCursor))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WalletTransactionListResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson22b96abEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WalletTransactionListResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson22b96abEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WalletTransactionListResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson22b96abDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WalletTransactionListResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson22b96abDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto1(l, v)
}
func easyjson22b96abDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto2(in *jlexer.Lexer, out *WalletResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "balance":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Balance = int64(in.Int64())
			}
		case "currency":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Currency = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson22b96abEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto2(out *jwriter.Writer, in WalletResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"balance\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Balance))
	}
	{
		const prefix string = ",\"currency\":"
		out.RawString(prefix)
		out.String(string(in.Currency))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WalletResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson22b96abEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WalletResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson22b96abEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WalletResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson22b96abDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WalletResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson22b96abDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto2(l, v)
}
func easyjson22b96abDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto3(in *jlexer.Lexer, out *TopupWalletResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "balance":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Balance = int64(in.Int64())
			}
		case "payment_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PaymentID = int64(in.Int64())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "confirmation_url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ConfirmationURL = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson22b96abEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto3(out *jwriter.Writer, in TopupWalletResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"balance\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Balance))
	}
	{
		const prefix string = ",\"payment_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.PaymentID))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	if in.ConfirmationURL != "" {
		const prefix string = ",\"confirmation_url\":"
		out.RawString(prefix)
		out.String(string(in.ConfirmationURL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TopupWalletResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson22b96abEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TopupWalletResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson22b96abEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TopupWalletResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson22b96abDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TopupWalletResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson22b96abDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto3(l, v)
}
func easyjson22b96abDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto4(in *jlexer.Lexer, out *TopupWalletRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "amount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Amount = int64(in.Int64())
			}
		case "idempotency_key":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IdempotencyKey = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson22b96abEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto4(out *jwriter.Writer, in TopupWalletRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Amount))
	}
	{
		const prefix string = ",\"idempotency_key\":"
		out.RawString(prefix)
		out.String(string(in.IdempotencyKey))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TopupWalletRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson22b96abEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TopupWalletRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson22b96abEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TopupWalletRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson22b96abDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TopupWalletRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson22b96abDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto4(l, v)
}
func easyjson22b96abDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto5(in *jlexer.Lexer, out *PaymentStatusResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "payment_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PaymentID = int64(in.Int64())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "amount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Amount = int64(in.Int64())
			}
		case "confirmation_url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ConfirmationURL = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson22b96abEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto5(out *jwriter.Writer, in PaymentStatusResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"payment_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.PaymentID))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix)
		out.Int64(int64(in.Amount))
	}
	if in.ConfirmationURL != "" {
		const prefix string = ",\"confirmation_url\":"
		out.RawString(prefix)
		out.String(string(in.ConfirmationURL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PaymentStatusResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson22b96abEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PaymentStatusResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson22b96abEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PaymentStatusResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson22b96abDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PaymentStatusResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson22b96abDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesCommerceInternalDomainDto5(l, v)
}
