package ads

import (
	"sync"
	"time"

	models "github.com/go-park-mail-ru/2026_1_VKernelTeam/clover/internal/domain/models"
)

// AdsRepository отвечает за доступ к данным
type AdsRepository struct {
	mu   sync.RWMutex
	Data []models.Ad // список объявлений
}

func NewAdsRepository() *AdsRepository {
	return &AdsRepository{
		Data: generateMockAds(),
	}
}

// generateMockAds возвращает ровно карточки с заполненными основными полями
func generateMockAds() []models.Ad {
	now := time.Now()

	return []models.Ad{
		{
			ID:             1,
			SellerID:       101,
			CategoryID:     1,
			Title:          "MacBook Pro 16 M1 Max",
			Description:    "Отличное состояние, полный комплект, использовался только для программирования. Батарея 95%.",
			Price:          250000,
			Status:         "active",
			Location:       "Москва",
			Photos:         []string{"/static/img/1.png"},
			ViewsCount:     150,
			FavoritesCount: 15,
			CreatedAt:      now.Add(-24 * time.Hour),
		},
		{
			ID:             2,
			SellerID:       102,
			CategoryID:     2,
			Title:          "Диван-кровать Икеа",
			Description:    "Хорошее состояние, есть небольшие пятна на обивке. Только самовывоз.",
			Price:          50000,
			Status:         "active",
			Location:       "Санкт-Петербург",
			Photos:         []string{"/static/img/2.png"},
			ViewsCount:     45,
			FavoritesCount: 3,
			CreatedAt:      now.Add(-48 * time.Hour),
		},
		{
			ID:             3,
			SellerID:       103,
			CategoryID:     3,
			Title:          "Горный велосипед Stern",
			Description:    "Почти новый, катались всего пару раз. Рама 20 дюймов, колеса 27.5.",
			Price:          55000,
			Status:         "active",
			Location:       "Казань",
			Photos:         []string{"/static/img/3.png"},
			ViewsCount:     12,
			FavoritesCount: 1,
			CreatedAt:      now.Add(-72 * time.Hour),
		},
		{
			ID:             4,
			SellerID:       104,
			CategoryID:     4,
			Title:          "Комплект книг Гарри Поттер",
			Description:    "Полное собрание от издательства РОСМЭН. Идеальное состояние, как новые.",
			Price:          0,
			Status:         "active",
			Location:       "Новосибирск",
			Photos:         []string{"/static/img/4.png"},
			ViewsCount:     300,
			FavoritesCount: 42,
			CreatedAt:      now.Add(-2 * time.Hour),
		},
		{
			ID:             5,
			SellerID:       105,
			CategoryID:     1,
			Title:          "iPhone 15 Pro Max 256GB",
			Description:    "Новый, запечатанный. Цвет Natural Titanium. Официальная гарантия.",
			Price:          125000,
			Status:         "active",
			Location:       "Москва",
			Photos:         []string{"/static/img/5.png", "/static/img/6.png"},
			ViewsCount:     890,
			FavoritesCount: 112,
			CreatedAt:      now.Add(-1 * time.Hour),
		},
		{
			ID:             6,
			SellerID:       106,
			CategoryID:     2,
			Title:          "Игровое кресло Cougar",
			Description:    "Эко-кожа, стальная рама, регулировка 4D подлокотников. Использовалось полгода.",
			Price:          18500,
			Status:         "active",
			Location:       "Екатеринбург",
			Photos:         []string{"/static/img/7.png"},
			ViewsCount:     210,
			FavoritesCount: 18,
			CreatedAt:      now.Add(-10 * time.Hour),
		},
		{
			ID:             7,
			SellerID:       107,
			CategoryID:     5,
			Title:          "Гитара Fender Stratocaster",
			Description:    "Made in Mexico, 2019 год. Шикарный звук, новые струны Ernie Ball.",
			Price:          85000,
			Status:         "active",
			Location:       "Краснодар",
			Photos:         []string{"/static/img/8.png", "/static/img/9.png"},
			ViewsCount:     345,
			FavoritesCount: 56,
			CreatedAt:      now.Add(-5 * time.Hour),
		},
		{
			ID:             8,
			SellerID:       108,
			CategoryID:     6,
			Title:          "Набор инструментов 120 предметов",
			Description:    "Сталь хром-ванадий. Пожизненная гарантия. Почти не пользовались.",
			Price:          7500,
			Status:         "active",
			Location:       "Нижний Новгород",
			Photos:         []string{"/static/img/10.png"},
			ViewsCount:     76,
			FavoritesCount: 12,
			CreatedAt:      now.Add(-15 * time.Hour),
		},
		{
			ID:             9,
			SellerID:       109,
			CategoryID:     1,
			Title:          "Sony PlayStation 5",
			Description:    "Версия с дисководом, 2 геймпада DualSense и игра в подарок.",
			Price:          49000,
			Status:         "active",
			Location:       "Владивосток",
			Photos:         []string{"/static/img/11.png"},
			ViewsCount:     560,
			FavoritesCount: 98,
			CreatedAt:      now.Add(-3 * time.Hour),
		},
		{
			ID:             10,
			SellerID:       110,
			CategoryID:     2,
			Title:          "Ковер персидский ручной работы",
			Description:    "Натуральная шерсть. Размер 2х3 метра. Состояние идеальное.",
			Price:          30000,
			Status:         "active",
			Location:       "Махачкала",
			Photos:         []string{"/static/img/12.png"},
			ViewsCount:     33,
			FavoritesCount: 5,
			CreatedAt:      now.Add(-96 * time.Hour),
		},
		{
			ID:             11,
			SellerID:       111,
			CategoryID:     4,
			Title:          "Коллекционное издание Булгакова",
			Description:    "Кожаный переплет, золотое тиснение. Ограниченная серия.",
			Price:          15000,
			Status:         "active",
			Location:       "Тула",
			Photos:         []string{"/static/img/13.png"},
			ViewsCount:     82,
			FavoritesCount: 21,
			CreatedAt:      now.Add(-20 * time.Hour),
		},
		{
			ID:             12,
			SellerID:       112,
			CategoryID:     7,
			Title:          "Палатка 3-х местная Tramp",
			Description:    "Двухслойная, влагозащита 5000мм. Идеальна для походов в горы.",
			Price:          12000,
			Status:         "active",
			Location:       "Сочи",
			Photos:         []string{"/static/img/14.png"},
			ViewsCount:     140,
			FavoritesCount: 25,
			CreatedAt:      now.Add(-12 * time.Hour),
		},
		{
			ID:             13,
			SellerID:       113,
			CategoryID:     1,
			Title:          "Монитор LG UltraWide 34\"",
			Description:    "IPS матрица, 144Hz. Широкий формат для работы и игр.",
			Price:          45000,
			Status:         "active",
			Location:       "Воронеж",
			Photos:         []string{"/static/img/15.png"},
			ViewsCount:     215,
			FavoritesCount: 30,
			CreatedAt:      now.Add(-18 * time.Hour),
		},
		{
			ID:             14,
			SellerID:       114,
			CategoryID:     3,
			Title:          "Сноуборд Burton Custom",
			Description:    "Универсальный борд, прогиб Camber. Крепления в комплекте.",
			Price:          35000,
			Status:         "active",
			Location:       "Челябинск",
			Photos:         []string{"/static/img/16.png"},
			ViewsCount:     320,
			FavoritesCount: 65,
			CreatedAt:      now.Add(-8 * time.Hour),
		},
		{
			ID:             15,
			SellerID:       115,
			CategoryID:     8,
			Title:          "Кофемашина DeLonghi Magnifica",
			Description:    "Автоматический капучинатор. Кофе как в кофейне.",
			Price:          28000,
			Status:         "active",
			Location:       "Ростов-на-Дону",
			Photos:         []string{"/static/img/17.png"},
			ViewsCount:     180,
			FavoritesCount: 22,
			CreatedAt:      now.Add(-4 * time.Hour),
		},
		{
			ID:             16,
			SellerID:       116,
			CategoryID:     1,
			Title:          "AirPods Pro 2 (USB-C)",
			Description:    "Оригинал, новые в пленке. Активное шумоподавление и прозрачность.",
			Price:          21000,
			Status:         "active",
			Location:       "Калининград",
			Photos:         []string{"/static/img/18.png"},
			ViewsCount:     640,
			FavoritesCount: 45,
			CreatedAt:      now.Add(-30 * time.Minute),
		},
		{
			ID:             17,
			SellerID:       117,
			CategoryID:     5,
			Title:          "Синтезатор Yamaha PSR",
			Description:    "61 клавиша, чувствительность к нажатию. Идеально для обучения.",
			Price:          32000,
			Status:         "active",
			Location:       "Самара",
			Photos:         []string{"/static/img/19.png"},
			ViewsCount:     54,
			FavoritesCount: 7,
			CreatedAt:      now.Add(-60 * time.Hour),
		},
		{
			ID:             18,
			SellerID:       118,
			CategoryID:     9,
			Title:          "Lego Technic Самосвал",
			Description:    "Огромная модель, все механизмы работают. Инструкция в наличии.",
			Price:          14000,
			Status:         "active",
			Location:       "Уфа",
			Photos:         []string{"/static/img/20.png"},
			ViewsCount:     112,
			FavoritesCount: 15,
			CreatedAt:      now.Add(-22 * time.Hour),
		},
		{
			ID:             19,
			SellerID:       119,
			CategoryID:     1,
			Title:          "Механическая клавиатура Keychron",
			Description:    "Алюминиевый корпус, Hot-swap, RGB подсветка. Смазанные переключатели.",
			Price:          16000,
			Status:         "active",
			Location:       "Омск",
			Photos:         []string{"/static/img/21.png"},
			ViewsCount:     195,
			FavoritesCount: 28,
			CreatedAt:      now.Add(-6 * time.Hour),
		},
		{
			ID:             20,
			SellerID:       120,
			CategoryID:     10,
			Title:          "Настольная игра 'Gloomhaven'",
			Description:    "Самая масштабная настолка. Огромная коробка весом 10кг. Состояние 5/5.",
			Price:          14500,
			Status:         "active",
			Location:       "Волгоград",
			Photos:         []string{"/static/img/22.png"},
			ViewsCount:     88,
			FavoritesCount: 14,
			CreatedAt:      now.Add(-14 * time.Hour),
		},
	}
}

// метод для получения данных (чтобы не обращаться к полю data напрямую)
func (r *AdsRepository) GetAll() []models.Ad {
	r.mu.RLock()
	defer r.mu.RUnlock()

	// создаем новый слайс и копируем туда данные
	result := make([]models.Ad, len(r.Data))
	copy(result, r.Data)
	return result
}
