// Code generated by MockGen. DO NOT EDIT.
// Source: wallet.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2026_1_VKernelTeam/clover/services/commerce/internal/domain/models"
	gomock "github.com/golang/mock/gomock"
	pgx "github.com/jackc/pgx/v5"
)

// MockTxRunner is a mock of TxRunner interface.
type MockTxRunner struct {
	ctrl     *gomock.Controller
	recorder *MockTxRunnerMockRecorder
}

// MockTxRunnerMockRecorder is the mock recorder for MockTxRunner.
type MockTxRunnerMockRecorder struct {
	mock *MockTxRunner
}

// NewMockTxRunner creates a new mock instance.
func NewMockTxRunner(ctrl *gomock.Controller) *MockTxRunner {
	mock := &MockTxRunner{ctrl: ctrl}
	mock.recorder = &MockTxRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxRunner) EXPECT() *MockTxRunnerMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockTxRunner) Begin(ctx context.Context) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockTxRunnerMockRecorder) Begin(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockTxRunner)(nil).Begin), ctx)
}

// MockWalletRepo is a mock of WalletRepo interface.
type MockWalletRepo struct {
	ctrl     *gomock.Controller
	recorder *MockWalletRepoMockRecorder
}

// MockWalletRepoMockRecorder is the mock recorder for MockWalletRepo.
type MockWalletRepoMockRecorder struct {
	mock *MockWalletRepo
}

// NewMockWalletRepo creates a new mock instance.
func NewMockWalletRepo(ctrl *gomock.Controller) *MockWalletRepo {
	mock := &MockWalletRepo{ctrl: ctrl}
	mock.recorder = &MockWalletRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletRepo) EXPECT() *MockWalletRepoMockRecorder {
	return m.recorder
}

// DecrementBalanceTx mocks base method.
func (m *MockWalletRepo) DecrementBalanceTx(ctx context.Context, tx pgx.Tx, userID, amount int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementBalanceTx", ctx, tx, userID, amount)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecrementBalanceTx indicates an expected call of DecrementBalanceTx.
func (mr *MockWalletRepoMockRecorder) DecrementBalanceTx(ctx, tx, userID, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementBalanceTx", reflect.TypeOf((*MockWalletRepo)(nil).DecrementBalanceTx), ctx, tx, userID, amount)
}

// Get mocks base method.
func (m *MockWalletRepo) Get(ctx context.Context, userID int64) (models.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID)
	ret0, _ := ret[0].(models.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockWalletRepoMockRecorder) Get(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockWalletRepo)(nil).Get), ctx, userID)
}

// GetForUpdateTx mocks base method.
func (m *MockWalletRepo) GetForUpdateTx(ctx context.Context, tx pgx.Tx, userID int64) (models.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForUpdateTx", ctx, tx, userID)
	ret0, _ := ret[0].(models.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetForUpdateTx indicates an expected call of GetForUpdateTx.
func (mr *MockWalletRepoMockRecorder) GetForUpdateTx(ctx, tx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForUpdateTx", reflect.TypeOf((*MockWalletRepo)(nil).GetForUpdateTx), ctx, tx, userID)
}

// GetOrCreate mocks base method.
func (m *MockWalletRepo) GetOrCreate(ctx context.Context, userID int64) (models.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreate", ctx, userID)
	ret0, _ := ret[0].(models.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreate indicates an expected call of GetOrCreate.
func (mr *MockWalletRepoMockRecorder) GetOrCreate(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreate", reflect.TypeOf((*MockWalletRepo)(nil).GetOrCreate), ctx, userID)
}

// GetTransactionByIdempotencyKey mocks base method.
func (m *MockWalletRepo) GetTransactionByIdempotencyKey(ctx context.Context, key string) (models.WalletTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionByIdempotencyKey", ctx, key)
	ret0, _ := ret[0].(models.WalletTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionByIdempotencyKey indicates an expected call of GetTransactionByIdempotencyKey.
func (mr *MockWalletRepoMockRecorder) GetTransactionByIdempotencyKey(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionByIdempotencyKey", reflect.TypeOf((*MockWalletRepo)(nil).GetTransactionByIdempotencyKey), ctx, key)
}

// IncrementBalanceTx mocks base method.
func (m *MockWalletRepo) IncrementBalanceTx(ctx context.Context, tx pgx.Tx, userID, amount int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementBalanceTx", ctx, tx, userID, amount)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementBalanceTx indicates an expected call of IncrementBalanceTx.
func (mr *MockWalletRepoMockRecorder) IncrementBalanceTx(ctx, tx, userID, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementBalanceTx", reflect.TypeOf((*MockWalletRepo)(nil).IncrementBalanceTx), ctx, tx, userID, amount)
}

// InsertTransactionTx mocks base method.
func (m *MockWalletRepo) InsertTransactionTx(ctx context.Context, tx pgx.Tx, userID, amount int64, txType string, referenceID *int64, idempotencyKey *string) (models.WalletTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertTransactionTx", ctx, tx, userID, amount, txType, referenceID, idempotencyKey)
	ret0, _ := ret[0].(models.WalletTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertTransactionTx indicates an expected call of InsertTransactionTx.
func (mr *MockWalletRepoMockRecorder) InsertTransactionTx(ctx, tx, userID, amount, txType, referenceID, idempotencyKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertTransactionTx", reflect.TypeOf((*MockWalletRepo)(nil).InsertTransactionTx), ctx, tx, userID, amount, txType, referenceID, idempotencyKey)
}

// ListTransactionsByUser mocks base method.
func (m *MockWalletRepo) ListTransactionsByUser(ctx context.Context, userID, cursor int64, limit int) ([]models.WalletTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransactionsByUser", ctx, userID, cursor, limit)
	ret0, _ := ret[0].([]models.WalletTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransactionsByUser indicates an expected call of ListTransactionsByUser.
func (mr *MockWalletRepoMockRecorder) ListTransactionsByUser(ctx, userID, cursor, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactionsByUser", reflect.TypeOf((*MockWalletRepo)(nil).ListTransactionsByUser), ctx, userID, cursor, limit)
}

// MockPaymentRepo is a mock of PaymentRepo interface.
type MockPaymentRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentRepoMockRecorder
}

// MockPaymentRepoMockRecorder is the mock recorder for MockPaymentRepo.
type MockPaymentRepoMockRecorder struct {
	mock *MockPaymentRepo
}

// NewMockPaymentRepo creates a new mock instance.
func NewMockPaymentRepo(ctrl *gomock.Controller) *MockPaymentRepo {
	mock := &MockPaymentRepo{ctrl: ctrl}
	mock.recorder = &MockPaymentRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentRepo) EXPECT() *MockPaymentRepoMockRecorder {
	return m.recorder
}

// InsertTx mocks base method.
func (m *MockPaymentRepo) InsertTx(ctx context.Context, tx pgx.Tx, userID, amount int64, status, provider string, providerRef *string) (models.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertTx", ctx, tx, userID, amount, status, provider, providerRef)
	ret0, _ := ret[0].(models.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertTx indicates an expected call of InsertTx.
func (mr *MockPaymentRepoMockRecorder) InsertTx(ctx, tx, userID, amount, status, provider, providerRef interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertTx", reflect.TypeOf((*MockPaymentRepo)(nil).InsertTx), ctx, tx, userID, amount, status, provider, providerRef)
}

// MockPaymentProvider is a mock of PaymentProvider interface.
type MockPaymentProvider struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentProviderMockRecorder
}

// MockPaymentProviderMockRecorder is the mock recorder for MockPaymentProvider.
type MockPaymentProviderMockRecorder struct {
	mock *MockPaymentProvider
}

// NewMockPaymentProvider creates a new mock instance.
func NewMockPaymentProvider(ctrl *gomock.Controller) *MockPaymentProvider {
	mock := &MockPaymentProvider{ctrl: ctrl}
	mock.recorder = &MockPaymentProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentProvider) EXPECT() *MockPaymentProviderMockRecorder {
	return m.recorder
}

// InitPayment mocks base method.
func (m *MockPaymentProvider) InitPayment(ctx context.Context, p models.Payment) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitPayment", ctx, p)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// InitPayment indicates an expected call of InitPayment.
func (mr *MockPaymentProviderMockRecorder) InitPayment(ctx, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitPayment", reflect.TypeOf((*MockPaymentProvider)(nil).InitPayment), ctx, p)
}
