// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/http/app.go

// Package mock_httpapp is a generated GoMock package.
package mock_httpapp

import (
	context "context"
	multipart "mime/multipart"
	reflect "reflect"
	time "time"

	dto "github.com/go-park-mail-ru/2026_1_VKernelTeam/clover/internal/domain/dto"
	models "github.com/go-park-mail-ru/2026_1_VKernelTeam/clover/internal/domain/models"
	gomock "github.com/golang/mock/gomock"
)

// MockAuth is a mock of Auth interface.
type MockAuth struct {
	ctrl     *gomock.Controller
	recorder *MockAuthMockRecorder
}

// MockAuthMockRecorder is the mock recorder for MockAuth.
type MockAuthMockRecorder struct {
	mock *MockAuth
}

// NewMockAuth creates a new mock instance.
func NewMockAuth(ctrl *gomock.Controller) *MockAuth {
	mock := &MockAuth{ctrl: ctrl}
	mock.recorder = &MockAuthMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuth) EXPECT() *MockAuthMockRecorder {
	return m.recorder
}

// GetProfile mocks base method.
func (m *MockAuth) GetProfile(ctx context.Context, userID int64) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", ctx, userID)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockAuthMockRecorder) GetProfile(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockAuth)(nil).GetProfile), ctx, userID)
}

// Login mocks base method.
func (m *MockAuth) Login(ctx context.Context, email, password string) (string, string, models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(models.User)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// Login indicates an expected call of Login.
func (mr *MockAuthMockRecorder) Login(ctx, email, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuth)(nil).Login), ctx, email, password)
}

// Logout mocks base method.
func (m *MockAuth) Logout(ctx context.Context, jti string, exp time.Time, refreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, jti, exp, refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthMockRecorder) Logout(ctx, jti, exp, refreshToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuth)(nil).Logout), ctx, jti, exp, refreshToken)
}

// Refresh mocks base method.
func (m *MockAuth) Refresh(ctx context.Context, refreshToken string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, refreshToken)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Refresh indicates an expected call of Refresh.
func (mr *MockAuthMockRecorder) Refresh(ctx, refreshToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockAuth)(nil).Refresh), ctx, refreshToken)
}

// RegisterNewUser mocks base method.
func (m *MockAuth) RegisterNewUser(ctx context.Context, email, password, name string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterNewUser", ctx, email, password, name)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterNewUser indicates an expected call of RegisterNewUser.
func (mr *MockAuthMockRecorder) RegisterNewUser(ctx, email, password, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterNewUser", reflect.TypeOf((*MockAuth)(nil).RegisterNewUser), ctx, email, password, name)
}

// UpdateAvatar mocks base method.
func (m *MockAuth) UpdateAvatar(ctx context.Context, userID int64, file multipart.File, filename string) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAvatar", ctx, userID, file, filename)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAvatar indicates an expected call of UpdateAvatar.
func (mr *MockAuthMockRecorder) UpdateAvatar(ctx, userID, file, filename interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAvatar", reflect.TypeOf((*MockAuth)(nil).UpdateAvatar), ctx, userID, file, filename)
}

// UpdateProfile mocks base method.
func (m *MockAuth) UpdateProfile(ctx context.Context, userID int64, name string) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, userID, name)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockAuthMockRecorder) UpdateProfile(ctx, userID, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockAuth)(nil).UpdateProfile), ctx, userID, name)
}

// ValidateTokenAndGetUser mocks base method.
func (m *MockAuth) ValidateTokenAndGetUser(ctx context.Context, tokenString string) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateTokenAndGetUser", ctx, tokenString)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateTokenAndGetUser indicates an expected call of ValidateTokenAndGetUser.
func (mr *MockAuthMockRecorder) ValidateTokenAndGetUser(ctx, tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateTokenAndGetUser", reflect.TypeOf((*MockAuth)(nil).ValidateTokenAndGetUser), ctx, tokenString)
}

// MockAds is a mock of Ads interface.
type MockAds struct {
	ctrl     *gomock.Controller
	recorder *MockAdsMockRecorder
}

// MockAdsMockRecorder is the mock recorder for MockAds.
type MockAdsMockRecorder struct {
	mock *MockAds
}

// NewMockAds creates a new mock instance.
func NewMockAds(ctrl *gomock.Controller) *MockAds {
	mock := &MockAds{ctrl: ctrl}
	mock.recorder = &MockAdsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAds) EXPECT() *MockAdsMockRecorder {
	return m.recorder
}

// AddFavorite mocks base method.
func (m *MockAds) AddFavorite(ctx context.Context, userID, adID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFavorite", ctx, userID, adID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFavorite indicates an expected call of AddFavorite.
func (mr *MockAdsMockRecorder) AddFavorite(ctx, userID, adID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFavorite", reflect.TypeOf((*MockAds)(nil).AddFavorite), ctx, userID, adID)
}

// CloseAd mocks base method.
func (m *MockAds) CloseAd(ctx context.Context, id, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseAd", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseAd indicates an expected call of CloseAd.
func (mr *MockAdsMockRecorder) CloseAd(ctx, id, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseAd", reflect.TypeOf((*MockAds)(nil).CloseAd), ctx, id, userID)
}

// CreateAd mocks base method.
func (m *MockAds) CreateAd(ctx context.Context, req *dto.CreateAdRequest) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAd", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAd indicates an expected call of CreateAd.
func (mr *MockAdsMockRecorder) CreateAd(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAd", reflect.TypeOf((*MockAds)(nil).CreateAd), ctx, req)
}

// DeleteAd mocks base method.
func (m *MockAds) DeleteAd(ctx context.Context, id, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAd", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAd indicates an expected call of DeleteAd.
func (mr *MockAdsMockRecorder) DeleteAd(ctx, id, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAd", reflect.TypeOf((*MockAds)(nil).DeleteAd), ctx, id, userID)
}

// GetAdByID mocks base method.
func (m *MockAds) GetAdByID(ctx context.Context, id int64) (models.Ad, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdByID", ctx, id)
	ret0, _ := ret[0].(models.Ad)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdByID indicates an expected call of GetAdByID.
func (mr *MockAdsMockRecorder) GetAdByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdByID", reflect.TypeOf((*MockAds)(nil).GetAdByID), ctx, id)
}

// GetAdsByUserID mocks base method.
func (m *MockAds) GetAdsByUserID(ctx context.Context, userID int64) ([]models.Ad, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdsByUserID", ctx, userID)
	ret0, _ := ret[0].([]models.Ad)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdsByUserID indicates an expected call of GetAdsByUserID.
func (mr *MockAdsMockRecorder) GetAdsByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdsByUserID", reflect.TypeOf((*MockAds)(nil).GetAdsByUserID), ctx, userID)
}

// GetAllAds mocks base method.
func (m *MockAds) GetAllAds(ctx context.Context) ([]models.Ad, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllAds", ctx)
	ret0, _ := ret[0].([]models.Ad)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllAds indicates an expected call of GetAllAds.
func (mr *MockAdsMockRecorder) GetAllAds(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllAds", reflect.TypeOf((*MockAds)(nil).GetAllAds), ctx)
}

// GetCategoryCharacteristics mocks base method.
func (m *MockAds) GetCategoryCharacteristics(ctx context.Context, categoryID int64) ([]models.CategoryCharacteristic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryCharacteristics", ctx, categoryID)
	ret0, _ := ret[0].([]models.CategoryCharacteristic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryCharacteristics indicates an expected call of GetCategoryCharacteristics.
func (mr *MockAdsMockRecorder) GetCategoryCharacteristics(ctx, categoryID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryCharacteristics", reflect.TypeOf((*MockAds)(nil).GetCategoryCharacteristics), ctx, categoryID)
}

// GetUserFavorites mocks base method.
func (m *MockAds) GetUserFavorites(ctx context.Context, userID int64) ([]models.Ad, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserFavorites", ctx, userID)
	ret0, _ := ret[0].([]models.Ad)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserFavorites indicates an expected call of GetUserFavorites.
func (mr *MockAdsMockRecorder) GetUserFavorites(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserFavorites", reflect.TypeOf((*MockAds)(nil).GetUserFavorites), ctx, userID)
}

// RemoveFavorite mocks base method.
func (m *MockAds) RemoveFavorite(ctx context.Context, userID, adID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFavorite", ctx, userID, adID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFavorite indicates an expected call of RemoveFavorite.
func (mr *MockAdsMockRecorder) RemoveFavorite(ctx, userID, adID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFavorite", reflect.TypeOf((*MockAds)(nil).RemoveFavorite), ctx, userID, adID)
}

// SearchAds mocks base method.
func (m *MockAds) SearchAds(ctx context.Context, query string, categoryID int64) ([]models.Ad, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchAds", ctx, query, categoryID)
	ret0, _ := ret[0].([]models.Ad)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchAds indicates an expected call of SearchAds.
func (mr *MockAdsMockRecorder) SearchAds(ctx, query, categoryID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchAds", reflect.TypeOf((*MockAds)(nil).SearchAds), ctx, query, categoryID)
}

// UpdateAd mocks base method.
func (m *MockAds) UpdateAd(ctx context.Context, req *dto.UpdateAdRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAd", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAd indicates an expected call of UpdateAd.
func (mr *MockAdsMockRecorder) UpdateAd(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAd", reflect.TypeOf((*MockAds)(nil).UpdateAd), ctx, req)
}

// UploadAdPhotos mocks base method.
func (m *MockAds) UploadAdPhotos(ctx context.Context, files []multipart.File, filenames []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadAdPhotos", ctx, files, filenames)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadAdPhotos indicates an expected call of UploadAdPhotos.
func (mr *MockAdsMockRecorder) UploadAdPhotos(ctx, files, filenames interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadAdPhotos", reflect.TypeOf((*MockAds)(nil).UploadAdPhotos), ctx, files, filenames)
}

// MockCart is a mock of Cart interface.
type MockCart struct {
	ctrl     *gomock.Controller
	recorder *MockCartMockRecorder
}

// MockCartMockRecorder is the mock recorder for MockCart.
type MockCartMockRecorder struct {
	mock *MockCart
}

// NewMockCart creates a new mock instance.
func NewMockCart(ctrl *gomock.Controller) *MockCart {
	mock := &MockCart{ctrl: ctrl}
	mock.recorder = &MockCartMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCart) EXPECT() *MockCartMockRecorder {
	return m.recorder
}

// AddToCart mocks base method.
func (m *MockCart) AddToCart(ctx context.Context, userID, productID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddToCart", ctx, userID, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddToCart indicates an expected call of AddToCart.
func (mr *MockCartMockRecorder) AddToCart(ctx, userID, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToCart", reflect.TypeOf((*MockCart)(nil).AddToCart), ctx, userID, productID)
}

// GetCart mocks base method.
func (m *MockCart) GetCart(ctx context.Context, userID int64) (*dto.CartResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCart", ctx, userID)
	ret0, _ := ret[0].(*dto.CartResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCart indicates an expected call of GetCart.
func (mr *MockCartMockRecorder) GetCart(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCart", reflect.TypeOf((*MockCart)(nil).GetCart), ctx, userID)
}

// RemoveFromCart mocks base method.
func (m *MockCart) RemoveFromCart(ctx context.Context, userID, productID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFromCart", ctx, userID, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFromCart indicates an expected call of RemoveFromCart.
func (mr *MockCartMockRecorder) RemoveFromCart(ctx, userID, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFromCart", reflect.TypeOf((*MockCart)(nil).RemoveFromCart), ctx, userID, productID)
}

// MockChat is a mock of Chat interface.
type MockChat struct {
	ctrl     *gomock.Controller
	recorder *MockChatMockRecorder
}

// MockChatMockRecorder is the mock recorder for MockChat.
type MockChatMockRecorder struct {
	mock *MockChat
}

// NewMockChat creates a new mock instance.
func NewMockChat(ctrl *gomock.Controller) *MockChat {
	mock := &MockChat{ctrl: ctrl}
	mock.recorder = &MockChatMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChat) EXPECT() *MockChatMockRecorder {
	return m.recorder
}

// ConfirmPurchase mocks base method.
func (m *MockChat) ConfirmPurchase(ctx context.Context, chatID, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmPurchase", ctx, chatID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmPurchase indicates an expected call of ConfirmPurchase.
func (mr *MockChatMockRecorder) ConfirmPurchase(ctx, chatID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmPurchase", reflect.TypeOf((*MockChat)(nil).ConfirmPurchase), ctx, chatID, userID)
}

// CreateOrderRequest mocks base method.
func (m *MockChat) CreateOrderRequest(ctx context.Context, adID, buyerID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrderRequest", ctx, adID, buyerID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrderRequest indicates an expected call of CreateOrderRequest.
func (mr *MockChatMockRecorder) CreateOrderRequest(ctx, adID, buyerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrderRequest", reflect.TypeOf((*MockChat)(nil).CreateOrderRequest), ctx, adID, buyerID)
}

// GetAllChats mocks base method.
func (m *MockChat) GetAllChats(ctx context.Context, userID int64) (dto.ChatListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllChats", ctx, userID)
	ret0, _ := ret[0].(dto.ChatListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllChats indicates an expected call of GetAllChats.
func (mr *MockChatMockRecorder) GetAllChats(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllChats", reflect.TypeOf((*MockChat)(nil).GetAllChats), ctx, userID)
}

// GetChat mocks base method.
func (m *MockChat) GetChat(ctx context.Context, chatID, userID int64) (dto.ChatDetailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChat", ctx, chatID, userID)
	ret0, _ := ret[0].(dto.ChatDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChat indicates an expected call of GetChat.
func (mr *MockChatMockRecorder) GetChat(ctx, chatID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChat", reflect.TypeOf((*MockChat)(nil).GetChat), ctx, chatID, userID)
}

// MockTokenChecker is a mock of TokenChecker interface.
type MockTokenChecker struct {
	ctrl     *gomock.Controller
	recorder *MockTokenCheckerMockRecorder
}

// MockTokenCheckerMockRecorder is the mock recorder for MockTokenChecker.
type MockTokenCheckerMockRecorder struct {
	mock *MockTokenChecker
}

// NewMockTokenChecker creates a new mock instance.
func NewMockTokenChecker(ctrl *gomock.Controller) *MockTokenChecker {
	mock := &MockTokenChecker{ctrl: ctrl}
	mock.recorder = &MockTokenCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenChecker) EXPECT() *MockTokenCheckerMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockTokenChecker) Check(jti string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", jti)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockTokenCheckerMockRecorder) Check(jti interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockTokenChecker)(nil).Check), jti)
}
