// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson9e1087fdDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesAuthInternalDomainModels(in *jlexer.Lexer, out *User) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "email":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Email = string(in.String())
			}
		case "avatar_path":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AvatarPath = string(in.String())
			}
		case "rating":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Rating = float64(in.Float64())
			}
		case "role":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Role = string(in.String())
			}
		case "reviews_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ReviewsCount = int(in.Int())
			}
		case "ads_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AdsCount = int(in.Int())
			}
		case "favorites_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FavoritesCount = int(in.Int())
			}
		case "cart_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CartCount = int(in.Int())
			}
		case "unread_messages_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MessagesCount = int(in.Int())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "updated_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9e1087fdEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesAuthInternalDomainModels(out *jwriter.Writer, in User) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"avatar_path\":"
		out.RawString(prefix)
		out.String(string(in.AvatarPath))
	}
	{
		const prefix string = ",\"rating\":"
		out.RawString(prefix)
		out.Float64(float64(in.Rating))
	}
	{
		const prefix string = ",\"role\":"
		out.RawString(prefix)
		out.String(string(in.Role))
	}
	{
		const prefix string = ",\"reviews_count\":"
		out.RawString(prefix)
		out.Int(int(in.ReviewsCount))
	}
	{
		const prefix string = ",\"ads_count\":"
		out.RawString(prefix)
		out.Int(int(in.AdsCount))
	}
	{
		const prefix string = ",\"favorites_count\":"
		out.RawString(prefix)
		out.Int(int(in.FavoritesCount))
	}
	{
		const prefix string = ",\"cart_count\":"
		out.RawString(prefix)
		out.Int(int(in.CartCount))
	}
	{
		const prefix string = ",\"unread_messages_count\":"
		out.RawString(prefix)
		out.Int(int(in.MessagesCount))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v User) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9e1087fdEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesAuthInternalDomainModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v User) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9e1087fdEncodeGithubComGoParkMailRu20261VKernelTeamCloverServicesAuthInternalDomainModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *User) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9e1087fdDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesAuthInternalDomainModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *User) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9e1087fdDecodeGithubComGoParkMailRu20261VKernelTeamCloverServicesAuthInternalDomainModels(l, v)
}
